-- Synthetic commerce fixtures: always run within the runner's rollback scope.
do $$
declare
 aa uuid:=gen_random_uuid(); ca uuid:=gen_random_uuid(); sa uuid:=gen_random_uuid(); na uuid:=gen_random_uuid(); oa uuid:=gen_random_uuid();
 admin_id uuid; owner_id uuid; staff_id uuid; next_id uuid; other_id uuid; service_id uuid; creator_one uuid; creator_two uuid;
 rid uuid; second_request uuid; proposal_one uuid; proposal_two uuid; cancelled_quote uuid; q1 uuid; q2 uuid; oid uuid; customer_id uuid;
 denied boolean; input jsonb; output jsonb; original_projects bigint; original_invoices bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data) values
 (aa,aa||'@example.invalid','{"full_name":"Commerce admin"}'),(ca,ca||'@example.invalid','{"full_name":"Commerce business"}'),
 (sa,sa||'@example.invalid','{"full_name":"Commerce staff"}'),(na,na||'@example.invalid','{"full_name":"Commerce transfer"}'),(oa,oa||'@example.invalid','{"full_name":"Commerce other"}');
 select id into admin_id from profiles where auth_user_id=aa;
 select id into owner_id from profiles where auth_user_id=ca;
 select id into staff_id from profiles where auth_user_id=sa;
 select id into next_id from profiles where auth_user_id=na;
 select id into other_id from profiles where auth_user_id=oa;
 update profiles set role='ADMIN' where id=admin_id;
 update profiles set role='BUSINESS' where id=owner_id;
 update profiles set role='STAFF' where id in (staff_id,next_id);
 select id into customer_id from customers where profile_id=owner_id;
 insert into services(name,slug,active) values('Commerce service',gen_random_uuid()::text,true) returning id into service_id;
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Creator One','Video','AVAILABLE') returning id into creator_one;
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Creator Two','Video','AVAILABLE') returning id into creator_two;
 select count(*) into original_projects from projects; select count(*) into original_invoices from invoices;
 rid:=(request_action(owner_id,null,'create',jsonb_build_object('service_id',service_id,'title','Commerce brief','brief','Test only','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform request_action(staff_id,rid,'claim','{}');
 denied:=false; begin perform request_commerce_action(staff_id,rid,'propose',jsonb_build_object('creator_id',creator_one,'reason','Too early')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Proposal bypasses consultation'; end if;
 perform request_action(staff_id,rid,'status','{"status":"CONSULTING"}');
 proposal_one:=(request_commerce_action(staff_id,rid,'propose',jsonb_build_object('creator_id',creator_one,'reason','Video experience','estimated_price',1000))->>'id')::uuid;
 proposal_two:=(request_commerce_action(staff_id,rid,'propose',jsonb_build_object('creator_id',creator_two,'reason','Alternative approach'))->>'id')::uuid;
 if (select status from requests where id=rid)<>'CREATOR_SELECTION' or (select count(*) from creator_proposals where request_id=rid)<>2 then raise exception 'Multiple proposal workflow failed'; end if;
 if (select creator_snapshot from creator_proposals where id=proposal_one)?'profile_id' then raise exception 'Proposal exposes private account identity'; end if;
 denied:=false; begin perform request_commerce_action(staff_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_one)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Staff impersonates customer selection'; end if;
 denied:=false; begin perform request_commerce_action(other_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_one)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Other customer selects proposal'; end if;
 perform request_commerce_action(owner_id,rid,'proposal_shortlist',jsonb_build_object('proposal_id',proposal_one));
 perform request_commerce_action(owner_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_two));
 perform request_commerce_action(owner_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_one));
 if (select count(*) from creator_proposals where request_id=rid and status='SELECTED')<>1 or (select selected_proposal_id from requests where id=rid)<>proposal_one then raise exception 'Selected creator is not unique'; end if;
 input:=jsonb_build_object('items',jsonb_build_array(jsonb_build_object('service_id',service_id,'description','Video production','quantity',3,'unit_price',333.33)),
 'discount',9.99,'tax_rate',10,'deposit_percent',30,'valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14,'revision_policy','Two revision rounds','notes','Public terms',
 'total',1,'deposit_amount',1,'remaining_amount',0);
 cancelled_quote:=(request_commerce_action(staff_id,rid,'quote_save',input)->>'id')::uuid;
 if (select total from quotations where id=cancelled_quote)<>1089 or (select deposit_amount from quotations where id=cancelled_quote)<>326.70 then raise exception 'Server totals/rounding trusted frontend'; end if;
 perform request_commerce_action(staff_id,rid,'quote_cancel',jsonb_build_object('quote_id',cancelled_quote));
 q1:=(request_commerce_action(staff_id,rid,'quote_save',input)->>'id')::uuid;
 if q1=cancelled_quote or (select version from quotations where id=q1)<>2 then raise exception 'Cancelled draft was overwritten'; end if;
 if request_commerce_action(staff_id,rid,'quote_save',input)->>'id'<>q1::text then raise exception 'Draft save created multiple drafts'; end if;
 denied:=false; begin perform request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',q1)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Customer accepts unpublished draft'; end if;
 denied:=false; begin perform request_commerce_action(owner_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_two)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Quote creator snapshot silently changes'; end if;
 perform set_config('request.jwt.claim.sub',ca::text,true); execute 'set local role authenticated';
 if exists(select 1 from quotations where id in (cancelled_quote,q1)) or exists(select 1 from quotation_items where quotation_id=q1) then raise exception 'Unpublished or cancelled draft leaks to customer'; end if;
 execute 'reset role';
 perform request_commerce_action(staff_id,rid,'quote_send',jsonb_build_object('quote_id',q1));
 denied:=false; begin update quotations set total=1 where id=q1; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Published quote price is mutable'; end if;
 denied:=false; begin update quotation_items set unit_price=1 where quotation_id=q1; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Published quote items are mutable'; end if;
 denied:=false; begin perform manage_quotation(admin_id,q1,'cancel'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Legacy quotation RPC mutates commercial quote'; end if;
 perform request_commerce_action(owner_id,rid,'quote_view',jsonb_build_object('quote_id',q1));
 perform request_commerce_action(owner_id,rid,'quote_revise',jsonb_build_object('quote_id',q1,'reason','Include subtitles'));
 if (select status from quotations where id=q1)<>'REVISION_REQUESTED' or (select status from requests where id=rid)<>'QUOTE_REVISION' then raise exception 'Revision request state failed'; end if;
 perform request_action(staff_id,rid,'assign',jsonb_build_object('assigned_to',next_id,'reason','Private transfer reason'));
 if (select status from requests where id=rid)<>'QUOTE_REVISION' then raise exception 'Transfer resets commercial progress'; end if;
 denied:=false; begin perform request_commerce_action(staff_id,rid,'quote_save',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Transferred staff retains commerce writes'; end if;
 input:=input||jsonb_build_object('notes','Version 3 includes subtitles');
 q2:=(request_commerce_action(next_id,rid,'quote_save',input)->>'id')::uuid;
 if q2=q1 or (select version from quotations where id=q2)<>3 or (select previous_version_id from quotations where id=q2)<>q1 or (select notes from quotations where id=q1)<>'Public terms' then raise exception 'Quote revision overwrote original'; end if;
 perform request_commerce_action(next_id,rid,'quote_send',jsonb_build_object('quote_id',q2));
 denied:=false; begin perform request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',q1)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Customer accepts obsolete version'; end if;
 perform set_config('request.jwt.claim.sub',ca::text,true); execute 'set local role authenticated';
 if not exists(select 1 from quotations where id=q1) or not exists(select 1 from quotations where id=q2) or exists(select 1 from quotations where id=cancelled_quote) then raise exception 'Published quote history RLS failed'; end if;
 execute 'reset role';
 update profiles set active=false where id=next_id;
 denied:=false; begin perform request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',q2)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Order created with disabled operator'; end if;
 update profiles set active=true where id=next_id;
 output:=request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',q2)); oid:=(output->>'order_id')::uuid;
 if oid is null or (select status from orders where id=oid)<>'WAITING_CONTRACT' or (select status from requests where id=rid)<>'CONVERTED' then raise exception 'Accepted quote did not create waiting-contract order'; end if;
 if request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',q2))->>'order_id'<>oid::text or (select count(*) from orders where request_id=rid)<>1 then raise exception 'Accept retry creates another order'; end if;
 if (select total from orders where id=oid)<>1089 or (select assigned_to from orders where id=oid)<>next_id or (select count(*) from order_items where order_id=oid)<>1 then raise exception 'Order snapshots differ from accepted quote'; end if;
 if (select count(*) from projects)<>original_projects or (select count(*) from invoices)<>original_invoices then raise exception 'Accept prematurely creates project/invoice'; end if;
 perform request_action(owner_id,rid,'message','{"content":"Order conversation remains open"}');
 perform request_action(next_id,rid,'note','{"content":"Internal order note"}');
 denied:=false; begin perform request_action(owner_id,rid,'note','{"content":"Forbidden internal"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Customer writes internal order note'; end if;
 perform set_config('request.jwt.claim.sub',sa::text,true); execute 'set local role authenticated';
 if exists(select 1 from quotations where request_id=rid) or exists(select 1 from orders where id=oid) then raise exception 'Old assignee reads quote/order'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',oa::text,true); execute 'set local role authenticated';
 if exists(select 1 from creator_proposals where request_id=rid) or exists(select 1 from orders where id=oid) or exists(select 1 from order_items where order_id=oid) then raise exception 'Other customer reads commerce'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',na::text,true); execute 'set local role authenticated';
 if not exists(select 1 from orders where id=oid) or not exists(select 1 from order_items where order_id=oid) then raise exception 'Current staff lost order scope'; end if;
 execute 'reset role';
 if exists(select 1 from conversation_messages m join conversations c on c.id=m.conversation_id where c.request_id=rid and m.content like '%Private transfer reason%') then raise exception 'Transfer reason entered shared chat'; end if;
 if not exists(select 1 from audit_logs where action='ORDER_CREATED' and entity_id=rid) or not exists(select 1 from conversation_messages m join conversations c on c.id=m.conversation_id where c.request_id=rid and m.kind='QUOTE' and m.event_data->>'quote_id'=q2::text) then raise exception 'Commercial cards/audit missing'; end if;
 update orders set status='COMPLETED' where id=oid;
 denied:=false; begin perform request_action(owner_id,rid,'message','{"content":"Closed order"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Closed order conversation writable'; end if;
 -- A separate fixture exercises cross-request links and elapsed validity.
 second_request:=(request_action(owner_id,null,'create',jsonb_build_object('service_id',service_id,'title','Expiry brief','brief','Test only','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform request_action(next_id,second_request,'claim','{}');
 perform request_action(next_id,second_request,'status','{"status":"CONSULTING"}');
 proposal_two:=(request_commerce_action(next_id,second_request,'propose',jsonb_build_object('creator_id',creator_two,'reason','Expiry test'))->>'id')::uuid;
 denied:=false; begin perform request_commerce_action(owner_id,second_request,'proposal_select',jsonb_build_object('proposal_id',proposal_one)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Proposal selection crosses requests'; end if;
 perform request_commerce_action(owner_id,second_request,'proposal_select',jsonb_build_object('proposal_id',proposal_two));
 denied:=false; begin perform request_commerce_action(owner_id,second_request,'quote_accept',jsonb_build_object('quote_id',q2)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Quote acceptance crosses requests'; end if;
 q1:=(request_commerce_action(next_id,second_request,'quote_save',input)->>'id')::uuid;
 -- Simulate passage of time using a rollback-only draft before publication.
 update quotations set valid_until=(now() at time zone 'Asia/Ho_Chi_Minh')::date-1 where id=q1;
 denied:=false; begin perform request_commerce_action(next_id,second_request,'quote_send',jsonb_build_object('quote_id',q1)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Expired draft can be sent'; end if;
 update quotations set status='SENT',sent_at=now()-interval '2 days' where id=q1;
 update requests set status='QUOTE_SENT' where id=second_request;
 denied:=false; begin perform request_commerce_action(owner_id,second_request,'quote_accept',jsonb_build_object('quote_id',q1)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Expired quote can be accepted'; end if;
 perform request_commerce_action(next_id,second_request,'quote_expire',jsonb_build_object('quote_id',q1));
 if (select status from quotations where id=q1)<>'EXPIRED' or (select total from quotations where id=q1)<>1089 or (select status from requests where id=second_request)<>'QUOTE_REVISION' then raise exception 'Expiry loses quote history or blocks revision'; end if;
 q2:=(request_commerce_action(next_id,second_request,'quote_save',input)->>'id')::uuid;
 perform request_commerce_action(next_id,second_request,'quote_send',jsonb_build_object('quote_id',q2));
 denied:=false; begin perform request_commerce_action(next_id,second_request,'quote_expire',jsonb_build_object('quote_id',q2)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Valid quote can be expired early'; end if;
 if has_function_privilege('authenticated','public.request_commerce_action(uuid,uuid,text,jsonb)','execute') or has_function_privilege('service_role','public.request_action_consultation_base(uuid,uuid,text,jsonb)','execute') or has_table_privilege('authenticated','public.orders','insert') then raise exception 'Commerce client write privileges exposed'; end if;
end $$;
