-- Rollback-only contract/order-transfer fixtures. No signatures or bank receipts.
do $$
declare aa uuid:=gen_random_uuid(); ca uuid:=gen_random_uuid(); sa uuid:=gen_random_uuid(); na uuid:=gen_random_uuid(); xa uuid:=gen_random_uuid();
 admin_id uuid; owner_id uuid; staff_id uuid; next_id uuid; other_id uuid; service_id uuid; creator_id uuid;
 rid uuid; oid uuid; proposal_id uuid; qid uuid; draft_id uuid; c1 uuid; c2 uuid; ack_hash text; denied boolean; input jsonb;
 original_projects bigint; original_plans bigint; original_invoices bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data) values
 (aa,aa||'@example.invalid','{"full_name":"Contract admin"}'),(ca,ca||'@example.invalid','{"full_name":"Contract business"}'),
 (sa,sa||'@example.invalid','{"full_name":"Contract staff"}'),(na,na||'@example.invalid','{"full_name":"Contract transfer"}'),(xa,xa||'@example.invalid','{"full_name":"Contract other"}');
 select id into admin_id from profiles where auth_user_id=aa; select id into owner_id from profiles where auth_user_id=ca;
 select id into staff_id from profiles where auth_user_id=sa; select id into next_id from profiles where auth_user_id=na; select id into other_id from profiles where auth_user_id=xa;
 update profiles set role='ADMIN' where id=admin_id; update profiles set role='BUSINESS' where id=owner_id; update profiles set role='STAFF' where id in (staff_id,next_id);
 insert into services(name,slug,active) values('Contract service',gen_random_uuid()::text,true) returning id into service_id;
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Contract creator','Video','AVAILABLE') returning id into creator_id;
 select count(*) into original_projects from projects; select count(*) into original_plans from payment_plans; select count(*) into original_invoices from invoices;
 rid:=(request_action(owner_id,null,'create',jsonb_build_object('service_id',service_id,'title','Contract brief','brief','Rollback only','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform request_action(staff_id,rid,'claim','{}'); perform request_action(staff_id,rid,'status','{"status":"CONSULTING"}');
 proposal_id:=(request_commerce_action(staff_id,rid,'propose',jsonb_build_object('creator_id',creator_id,'reason','Test only'))->>'id')::uuid;
 perform request_commerce_action(owner_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_id));
 qid:=(request_commerce_action(staff_id,rid,'quote_save',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('service_id',service_id,'description','Video','quantity',1,'unit_price',1000)),'valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14,'revision_policy','Two rounds','deposit_percent',30))->>'id')::uuid;
 perform request_commerce_action(staff_id,rid,'quote_send',jsonb_build_object('quote_id',qid));
 oid:=(request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',qid))->>'order_id')::uuid;
 input:=jsonb_build_object('title','Terms','content','Exact terms version one','valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14);
 denied:=false; begin perform order_action(owner_id,oid,'contract_save',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Customer authors contract'; end if;
 denied:=false; begin perform order_action(other_id,oid,'contract_save',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Other owner accesses order actions'; end if;
 draft_id:=(order_action(staff_id,oid,'contract_save',input)->>'id')::uuid;
 if order_action(staff_id,oid,'contract_save',input)->>'id'<>draft_id::text then raise exception 'Contract save creates duplicate drafts'; end if;
 if (select quotation_id from order_contracts where id=draft_id)<>qid or (select request_id from order_contracts where id=draft_id)<>rid or length((select content_hash from order_contracts where id=draft_id))<>64 then raise exception 'Contract origin/content hash invalid'; end if;
 perform order_action(staff_id,oid,'contract_cancel',jsonb_build_object('contract_id',draft_id,'reason','Private draft cancel'));
 c1:=(order_action(staff_id,oid,'contract_save',input)->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',ca::text,true); execute 'set local role authenticated';
 if exists(select 1 from order_contracts where id in (draft_id,c1)) then raise exception 'Customer reads cancelled/unpublished contract draft'; end if;
 execute 'reset role';
 denied:=false; begin perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c1,'content_hash',(select content_hash from order_contracts where id=c1),'acknowledge',true)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Customer acknowledges unpublished draft'; end if;
 perform order_action(staff_id,oid,'contract_send',jsonb_build_object('contract_id',c1));
 denied:=false; begin update order_contracts set content='Changed published terms' where id=c1; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Published contract content is mutable'; end if;
 denied:=false; begin perform order_action(staff_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c1,'content_hash',(select content_hash from order_contracts where id=c1),'acknowledge',true)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Staff impersonates contract acknowledgment'; end if;
 perform order_action(owner_id,oid,'contract_view',jsonb_build_object('contract_id',c1));
 perform order_action(owner_id,oid,'contract_reject',jsonb_build_object('contract_id',c1,'reason','Clarify outputs'));
 if (select status from orders where id=oid)<>'WAITING_CONTRACT' or (select status from order_contracts where id=c1)<>'REJECTED' then raise exception 'Rejected contract prematurely unlocks payment'; end if;
 c2:=(order_action(staff_id,oid,'contract_save',input||'{"content":"Version two outputs clarified"}'::jsonb)->>'id')::uuid;
 if c2=c1 or (select previous_version_id from order_contracts where id=c2)<>c1 or (select content from order_contracts where id=c1)<>'Exact terms version one' then raise exception 'Revision overwrites contract history'; end if;
 -- Simulate elapsed time on a rollback-only draft before publication.
 update order_contracts set valid_until=(now() at time zone 'Asia/Ho_Chi_Minh')::date-1 where id=c2;
 denied:=false; begin perform order_action(staff_id,oid,'contract_send',jsonb_build_object('contract_id',c2)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Expired contract draft can be sent'; end if;
 update order_contracts set status='SENT',sent_at=now()-interval '2 days' where id=c2;
 denied:=false; begin perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c2,'content_hash',(select content_hash from order_contracts where id=c2),'acknowledge',true)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Expired contract acknowledged'; end if;
 perform order_action(staff_id,oid,'contract_expire',jsonb_build_object('contract_id',c2));
 c2:=(order_action(staff_id,oid,'contract_save',input||'{"content":"Final exact terms"}'::jsonb)->>'id')::uuid;
 perform order_action(staff_id,oid,'contract_send',jsonb_build_object('contract_id',c2));
 denied:=false; begin perform order_action(staff_id,oid,'contract_expire',jsonb_build_object('contract_id',c2)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Valid contract expired early'; end if;
 perform order_action(staff_id,oid,'assign',jsonb_build_object('assigned_to',next_id,'reason','Private order transfer'));
 if (select assigned_to from requests where id=rid)<>next_id or (select assigned_to from orders where id=oid)<>next_id or (select status from orders where id=oid)<>'WAITING_CONTRACT' or exists(select 1 from conversation_members m join conversations c on c.id=m.conversation_id where c.request_id=rid and m.profile_id=staff_id) then raise exception 'Order transfer does not synchronize assignment/membership'; end if;
 denied:=false; begin perform order_action(staff_id,oid,'contract_cancel',jsonb_build_object('contract_id',c2,'reason','Old operator')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Old operator retains order writes'; end if;
 perform set_config('request.jwt.claim.sub',sa::text,true); execute 'set local role authenticated';
 if exists(select 1 from order_contracts where order_id=oid) then raise exception 'Old operator reads contract'; end if;
 execute 'reset role';
 select content_hash into ack_hash from order_contracts where id=c2;
 denied:=false; begin perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c2,'content_hash',repeat('0',64),'acknowledge',true)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Stale/forged content hash accepted'; end if;
 denied:=false; begin perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c2,'content_hash',ack_hash,'acknowledge',false)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Acknowledgment checkbox ignored'; end if;
 denied:=false; begin perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c1,'content_hash',(select content_hash from order_contracts where id=c1),'acknowledge',true)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Obsolete contract accepted'; end if;
 update profiles set active=false where id=next_id;
 denied:=false; begin perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c2,'content_hash',ack_hash,'acknowledge',true)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Contract accepted with inactive operator'; end if;
 update profiles set active=true where id=next_id;
 perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c2,'content_hash',ack_hash,'acknowledge',true));
 if order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',c2,'content_hash',ack_hash,'acknowledge',true))->>'reused'<>'true' then raise exception 'Acknowledgment retry not idempotent'; end if;
 if (select status from orders where id=oid)<>'WAITING_PAYMENT' or (select status from order_contracts where id=c2)<>'ACKNOWLEDGED' or (select count(*) from contract_acknowledgments where order_id=oid)<>1 or (select contract_snapshot->>'content' from contract_acknowledgments where order_id=oid)<>'Final exact terms' or (select method from contract_acknowledgments where order_id=oid)<>'APPLICATION' then raise exception 'Acknowledgment evidence/gate invalid'; end if;
 denied:=false; begin update contract_acknowledgments set content_hash=repeat('0',64) where order_id=oid; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Acknowledgment evidence mutable'; end if;
 denied:=false; begin perform order_action(next_id,oid,'contract_save',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'New contract silently changes acknowledged order'; end if;
 perform set_config('request.jwt.claim.sub',ca::text,true); execute 'set local role authenticated';
 if not exists(select 1 from contract_acknowledgments where order_id=oid) or not exists(select 1 from order_contracts where id=c1) or exists(select 1 from order_contracts where id=draft_id) then raise exception 'Customer history/evidence scope invalid'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',xa::text,true); execute 'set local role authenticated';
 if exists(select 1 from contract_acknowledgments where order_id=oid) or exists(select 1 from order_contracts where order_id=oid) then raise exception 'Other owner reads contract evidence'; end if;
 execute 'reset role';
 if (select count(*) from projects)<>original_projects or (select count(*) from payment_plans)<>original_plans or (select count(*) from invoices)<>original_invoices then raise exception 'Acknowledgment fabricates project/payment/invoice'; end if;
 if exists(select 1 from conversation_messages m join conversations c on c.id=m.conversation_id where c.request_id=rid and m.content like '%Private%') or not exists(select 1 from conversation_messages m join conversations c on c.id=m.conversation_id where c.request_id=rid and m.kind='CONTRACT') or not exists(select 1 from audit_logs where action='CONTRACT_ACKNOWLEDGED' and metadata->>'order_id'=oid::text) then raise exception 'Contract events leak notes or omit evidence'; end if;
 if has_function_privilege('authenticated','public.order_action(uuid,uuid,text,jsonb)','execute') or has_table_privilege('authenticated','public.contract_acknowledgments','insert') then raise exception 'Contract client write privileges exposed'; end if;
end $$;
