do $$
declare aa uuid:=gen_random_uuid();xa uuid:=gen_random_uuid();ya uuid:=gen_random_uuid();admin_id uuid;x uuid;y uuid;cx uuid;cy uuid;skill uuid;cat uuid;pid uuid;input jsonb;data jsonb;denied boolean;url text;lease uuid;rid uuid;proposal uuid;owner_staff uuid;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(aa,aa||'@example.invalid','{"full_name":"Profile admin"}'),(xa,xa||'@example.invalid','{"full_name":"Profile Creator"}'),(ya,ya||'@example.invalid','{"full_name":"Other Creator"}');
 select id into admin_id from profiles where auth_user_id=aa;select id into x from profiles where auth_user_id=xa;select id into y from profiles where auth_user_id=ya;update profiles set role='ADMIN' where id=admin_id;
 insert into creator_profiles(slug,display_name,title,rating,review_count,completed_projects) values(gen_random_uuid()::text,'Projection profile','Video',4.9,999,888) returning id into cx;
 insert into creator_profiles(slug,display_name,title) values(gen_random_uuid()::text,'Other projection','Photo') returning id into cy;
 perform onboard_creator(admin_id,cx,x,jsonb_build_object('agreement_reference','PROFILE-X','signed_at',now()));perform onboard_creator(admin_id,cy,y,jsonb_build_object('agreement_reference','PROFILE-Y','signed_at',now()));
 data:=public_creator_detail((select slug from creator_profiles where id=cx));
 if data->>'rating' is not null or data->>'review_count'<>'0' or data->>'completed_projects'<>'0' or data ?| array['profile_id','social_links','email','phone','response_rate','response_time','completion_rate'] then raise exception 'Projection leaks identity or displays legacy synthetic metrics';end if;
 if public_creator_search('{"search":"Projection profile"}')->>'total'<>'1' then raise exception 'No-skill profile disappears from discovery';end if;
 insert into categories(name,slug) values(gen_random_uuid()::text,gen_random_uuid()::text) returning id into cat;
 insert into skills(name,slug) values('Unique profile skill '||gen_random_uuid(),gen_random_uuid()::text) returning id into skill;
 input:=jsonb_build_object('display_name','Projection profile','title','Video production','bio','Self introduction','location','Remote','university','','major','','experience_level','MID','availability','AVAILABLE','tools',jsonb_build_array('DaVinci Resolve'),'languages',jsonb_build_array('Tiếng Việt'),'skill_ids',jsonb_build_array(skill),'category_ids',jsonb_build_array(cat));
 perform creator_profile_action(x,'save',input);
 if not exists(select 1 from creator_skills where creator_id=cx and skill_id=skill) or public_creator_search(jsonb_build_object('search','DaVinci Resolve'))->>'total'<>'1' or public_creator_search(jsonb_build_object('skill',(select slug from skills where id=skill)))->>'total'<>'1' then raise exception 'Profile skills/tools are not searchable';end if;
 update creator_skills set proficiency=5 where creator_id=cx and skill_id=skill;perform creator_profile_action(x,'save',input);if (select proficiency from creator_skills where creator_id=cx and skill_id=skill)<>5 then raise exception 'Profile save silently resets existing skill proficiency';end if;
 if (select rating from creator_profiles where id=cx)<>4.9 or (select verified from creator_profiles where id=cx) then raise exception 'Self profile save rewrites controlled metrics';end if;
 denied:=false;begin perform creator_profile_action(admin_id,'save',input);exception when raise_exception then denied:=true;end;if not denied then raise exception 'Admin impersonates self-profile owner';end if;
 denied:=false;begin perform creator_profile_action(x,'save',input||jsonb_build_object('skill_ids',jsonb_build_array(gen_random_uuid())));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Unknown skill accepted';end if;
 input:=jsonb_build_object('title','Portfolio owned by Creator','description','Public result','category','Video','client','','project_year',2026,'rights_confirmed',true,'idempotency_key',gen_random_uuid());
 pid:=(creator_profile_action(x,'portfolio_save',input)->>'id')::uuid;
 if creator_profile_action(x,'portfolio_save',input)->>'id'<>pid::text then raise exception 'Portfolio retry duplicates';end if;
 denied:=false;begin perform creator_profile_action(x,'portfolio_save',input||'{"title":"Changed retry"}');exception when raise_exception then denied:=true;end;if not denied then raise exception 'Retry key silently changes portfolio';end if;
 denied:=false;begin perform creator_profile_action(y,'portfolio_delete',jsonb_build_object('id',pid));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Foreign portfolio deleted';end if;
 denied:=false;begin perform creator_profile_action(y,'portfolio_save',input||jsonb_build_object('id',pid));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Foreign portfolio edited';end if;
 denied:=false;begin perform creator_profile_action(x,'portfolio_save',input||'{"rights_confirmed":false}');exception when raise_exception then denied:=true;end;if not denied then raise exception 'Portfolio publishes without rights confirmation';end if;
 url:='https://example.invalid/storage/v1/object/public/creator-profile-assets/'||x||'/'||gen_random_uuid()||'.png';insert into storage.objects(bucket_id,name,metadata) values('creator-profile-assets',split_part(url,'/storage/v1/object/public/creator-profile-assets/',2),'{"size":100,"mimetype":"image/png"}');perform creator_profile_action(x,'cover',jsonb_build_object('image_url',url));
 denied:=false;begin perform creator_profile_action(x,'cover',jsonb_build_object('image_url',replace(url,x::text,y::text)));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Foreign cover path accepted';end if;
 if creator_profile_state(x)->'profile'->>'cover_url'<>url or (public_creator_detail((select slug from creator_profiles where id=cx))->'creator_portfolio'->0) ?| array['creator_id','idempotency_key'] then raise exception 'Self state/public portfolio projection failed';end if;
 perform creator_profile_action(x,'portfolio_delete',jsonb_build_object('id',pid));if exists(select 1 from creator_portfolio where id=pid) or not exists(select 1 from audit_logs where entity_id=pid and action='CREATOR_PROFILE_PORTFOLIO_DELETE') then raise exception 'Portfolio removal not audited';end if;
 -- Only synthetic requests from preceding rollback fixtures are used here.
 select r.id,r.assigned_to into rid,owner_staff from requests r join customers cust on cust.id=r.customer_id join profiles person on person.id=cust.profile_id join auth.users au on au.id=person.auth_user_id where au.email like '%@example.invalid' and r.title='Team request' and r.assigned_to is not null and exists(select 1 from orders where request_id=r.id and status in ('CONFIRMED','IN_PROGRESS')) limit 1;
 if rid is null then raise exception 'Missing synthetic request fixture';end if;
 insert into creator_proposals(request_id,creator_id,proposed_by,creator_snapshot,reason) values(rid,cx,owner_staff,'{}','Synthetic scheduling probe') returning id into proposal;
 insert into creator_assignments(request_id,creator_id,proposal_id,work_scope,invited_by,invited_at,expires_at) values(rid,cx,proposal,'Synthetic scope',owner_staff,clock_timestamp()-interval '10 minutes',clock_timestamp()+interval '5 minutes') returning id into lease;
 if public_creator_detail((select slug from creator_profiles where id=cx))->>'availability'<>'BUSY' then raise exception 'Pending reservation appears available';end if;
 if jsonb_array_length(creator_request_candidates(owner_staff,rid,'DaVinci Resolve')->'items')<>0 then raise exception 'Staff suggests a held Creator';end if;
 update creator_assignments set expires_at=clock_timestamp()-interval '1 minute' where id=lease;
 if public_creator_detail((select slug from creator_profiles where id=cx))->>'availability'<>'AVAILABLE' or jsonb_array_length(creator_request_candidates(owner_staff,rid,'DaVinci Resolve')->'items')<>1 then raise exception 'Expired lease still hides available Creator';end if;
 update creator_assignments set status='ACCEPTED' where id=lease;
 if public_creator_detail((select slug from creator_profiles where id=cx))->>'availability'<>'BUSY' then raise exception 'Accepted work does not mark Creator busy';end if;
 update creator_assignments set status='RELEASED' where id=lease;
 if public_creator_detail((select slug from creator_profiles where id=cx))->>'availability'<>'AVAILABLE' or creator_request_candidates(x,rid,'') is not null then raise exception 'Release or candidate role scope fails';end if;
 select public_creator_detail(cp.slug) into data from creator_profiles cp join profiles person on person.id=cp.profile_id join auth.users au on au.id=person.auth_user_id where au.email like '%@example.invalid' and exists(select 1 from order_creator_reviews where creator_id=cp.id) limit 1;
 if data is null or (data->>'review_count')::integer<1 or (data->>'completed_projects')::integer<1 or data->>'rating' is null then raise exception 'Verified completed-order metrics missing';end if;
 if public_completed_creator_reviews(data->>'slug',1)->>'rating' is distinct from data->>'rating' then raise exception 'Discovery and review detail ratings diverge';end if;
 update profiles set active=false where id=x;
 if public_creator_detail((select slug from creator_profiles where id=cx)) is not null or creator_profile_state(x) is not null or public_completed_creator_reviews((select slug from creator_profiles where id=cx),1) is not null then raise exception 'Suspended Creator remains publicly discoverable';end if;
 if has_function_privilege('authenticated','creator_profile_action(uuid,text,jsonb)','EXECUTE') or has_table_privilege('anon','creator_discovery_projection','SELECT') or has_table_privilege('authenticated','creator_profiles','SELECT') then raise exception 'Browser bypasses safe Creator projection';end if;
end $$;
