import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
process.env.NODE_ENV='test';process.env.SUPABASE_URL='http://127.0.0.1:59999';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';
const {app,apiLimiter}=await import('../dist/app.mjs');const {db}=await import('../dist/db.js');
const pid='11111111-1111-4111-8111-111111111111',oid='22222222-2222-4222-8222-222222222222',vid='33333333-3333-4333-8333-333333333333',qid='44444444-4444-4444-8444-444444444444';
let server,base;before(async()=>{server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}/api/creator/profile`;});after(()=>new Promise(resolve=>server.close(resolve)));
const headers={Authorization:'Bearer test-only','Content-Type':'application/json'},post=(path,body)=>fetch(base+path,{method:'POST',headers,body:JSON.stringify(body)});
async function identity(role,run,{allowed=true,rpcError=null,active=true}={}){
 apiLimiter.resetKey('127.0.0.1');const old={from:db.from,rpc:db.rpc,getUser:db.auth.getUser,storageFrom:db.storage.from},calls=[];
 db.auth.getUser=async()=>({data:{user:{id:pid}},error:null});
 db.from=table=>{let rows=table==='profiles'?[{id:pid,auth_user_id:pid,role,active,full_name:'Test',email:'qa@example.invalid'}]:table==='customers'?[{id:oid,profile_id:pid}]:[];return{select(){return this},eq(field,value){rows=rows.filter(row=>row[field]===value);return this},maybeSingle:async()=>({data:rows[0]||null,error:null})}};
 db.rpc=async(name,args)=>{calls.push({name,args});return{data:name==='creator_profile_state'?(allowed?{profile:{id:oid,slug:'sample'},portfolio:[],public:{review_count:0}}:null):name==='public_creator_search'?{items:[],total:0,page:1,limit:6}:name==='public_creator_detail'?(allowed?{slug:'sample',review_count:0}:null):{id:vid},error:name==='creator_profile_action'?rpcError:null}};
 db.storage.from=bucket=>({upload:async(path,_bytes,options)=>{calls.push({storage:'upload',bucket,path,options});return{data:{path},error:null};},remove:async paths=>{calls.push({storage:'remove',bucket,paths});return{data:[],error:null};},getPublicUrl:path=>({data:{publicUrl:`https://example.invalid/storage/v1/object/public/${bucket}/${path}`}})});

 try{await run(calls)}finally{db.from=old.from;db.rpc=old.rpc;db.auth.getUser=old.getUser;db.storage.from=old.storageFrom}
}


const save={display_name:'Creator',title:'Video',bio:'Profile',location:'Remote',university:'',major:'',experience_level:'MID',availability:'AVAILABLE',tools:['Resolve'],languages:['Vietnamese'],skill_ids:[],category_ids:[]};
const portfolio={title:'Public work',description:'I directed the video',category:'Video',client:'',rights_confirmed:true,idempotency_key:vid};
test('Creator profile requires authentication',async()=>assert.equal((await fetch(base)).status,401));
test('Other roles cannot read or edit self Creator professional profile',async()=>{for(const role of ['CUSTOMER','BUSINESS','STAFF','ADMIN'])await identity(role,async calls=>{assert.equal((await fetch(base,{headers})).status,403);assert.equal((await post('/save',save)).status,403);assert.equal(calls.length,0)})});
test('Own profile save binds actor to login and preserves strict editable fields',async()=>identity('CREATOR',async calls=>{assert.equal((await post('/save',save)).status,200);assert.deepEqual(calls.at(-1),{name:'creator_profile_action',args:{actor_id:pid,operation:'save',payload:save}})}));
test('Managed rating, verification, identity and booking state cannot be overposted',async()=>identity('CREATOR',async calls=>{for(const field of ['rating','verified','featured','profile_id','price_from','completed_projects'])assert.equal((await post('/save',{...save,[field]:5})).status,422);assert.equal((await post('/save',{...save,availability:'BUSY'})).status,422);assert.equal(calls.length,0)}));
test('Unlinked Creator receives actionable profile-required error',async()=>identity('CREATOR',async calls=>{assert.equal((await fetch(base,{headers})).status,409);assert.equal((await post('/save',save)).status,409);assert.equal(calls.some(c=>c.name==='creator_profile_action'),false)},{allowed:false}));
test('Invalid skill ID and excessive lists reject before persistence',async()=>identity('CREATOR',async calls=>{assert.equal((await post('/save',{...save,skill_ids:['invalid']})).status,422);assert.equal((await post('/save',{...save,tools:Array(21).fill('Tool')})).status,422);assert.equal((await post('/save',{...save,languages:[]})).status,422);assert.equal(calls.length,0)}));
test('Portfolio publication requires explicit rights and stable intent',async()=>identity('CREATOR',async calls=>{assert.equal((await post('/portfolio_save',{...portfolio,rights_confirmed:false})).status,422);assert.equal((await post('/portfolio_save',{...portfolio,idempotency_key:undefined})).status,422);assert.equal(calls.length,0);assert.equal((await post('/portfolio_save',portfolio)).status,200);assert.equal(calls.at(-1).args.payload.idempotency_key,vid)}));
test('Portfolio links reject scripts, credentials and foreign image ownership',async()=>identity('CREATOR',async calls=>{for(const project_url of ['javascript:alert(1)','http://example.invalid','https://name:pass@example.invalid/work'])assert.equal((await post('/portfolio_save',{...portfolio,project_url})).status,422);assert.equal((await post('/portfolio_save',{...portfolio,image_url:`https://example.invalid/storage/v1/object/public/creator-profile-assets/${qid}/${vid}.png`})).status,422);assert.equal(calls.some(c=>c.name==='creator_profile_action'),false)}));
test('Deletion and failed workflow do not report false success',async()=>identity('CREATOR',async()=>{const r=await post('/portfolio_delete',{id:vid});assert.equal(r.status,409);assert.equal((await r.json()).error.code,'INVALID_WORKFLOW')},{rpcError:{code:'P0001',message:'Không tìm thấy portfolio của bạn.'}}));
function imageBody({kind='cover',rights='true',fake=false}={}){const body=new FormData();body.append('kind',kind);body.append('rights_confirmed',rights);body.append('file',new Blob([fake?Buffer.from('fake'):Buffer.from([137,80,78,71,13,10,26,10,0])],{type:'image/png'}),'profile.png');return body;}
const imagePost=body=>fetch(base+'/images',{method:'POST',headers:{Authorization:headers.Authorization},body});
test('Public image upload requires rights and checks file signature before storage',async()=>identity('CREATOR',async calls=>{assert.equal((await imagePost(imageBody({rights:'false'}))).status,422);assert.equal((await imagePost(imageBody({fake:true}))).status,422);assert.equal(calls.some(c=>c.storage==='upload'),false)}));
test('Uploaded cover uses private server actor and owned public path',async()=>identity('CREATOR',async calls=>{const r=await imagePost(imageBody());assert.equal(r.status,201);assert.match((await r.json()).data.image_url,new RegExp('/'+pid+'/'));assert.equal(calls.at(-1).name,'creator_profile_action');assert.equal(calls.at(-1).args.actor_id,pid);assert.equal(calls.at(-1).args.operation,'cover')}));
test('Failed cover persistence removes its upload',async()=>identity('CREATOR',async calls=>{assert.equal((await imagePost(imageBody())).status,409);assert.equal(calls.at(-1).storage,'remove')},{rpcError:{code:'P0001',message:'Ảnh không hợp lệ.'}}));
test('Public search rejects caller identity and forwards only bounded safe filters',async()=>identity('CREATOR',async calls=>{const root=base.replace('/creator/profile','/public/creators');assert.equal((await fetch(root+'?actor_id='+pid)).status,422);assert.equal((await fetch(root+'?page=100001')).status,422);assert.equal(calls.length,0);assert.equal((await fetch(root+'?search=Resolve&availability=AVAILABLE')).status,200);assert.deepEqual(calls.at(-1),{name:'public_creator_search',args:{filters:{page:1,limit:6,search:'Resolve',availability:'AVAILABLE',sort:'recommended'}}})}));
test('Public detail hides inactive/absent Creator with 404',async()=>identity('CREATOR',async()=>assert.equal((await fetch(base.replace('/creator/profile','/public/creators')+'/sample')).status,404),{allowed:false}));
test('Inactive account cannot edit professional profile',async()=>identity('CREATOR',async calls=>{assert.equal((await post('/save',save)).status,403);assert.equal(calls.length,0)},{active:false}));
