-- Synthetic fixtures only; the runner rolls back every row and setting.
do $$
declare aa uuid:=gen_random_uuid(); ca uuid:=gen_random_uuid(); sa uuid:=gen_random_uuid(); sb uuid:=gen_random_uuid(); xa uuid:=gen_random_uuid(); ya uuid:=gen_random_uuid(); za uuid:=gen_random_uuid();
 a uuid; c uuid; s uuid; s2 uuid; x uuid; y uuid; z uuid; cx uuid; cy uuid; cz uuid; pz uuid; az uuid; svc uuid; rid uuid; r2 uuid; px uuid; py uuid; p2 uuid; ax uuid; ay uuid; q uuid; oid uuid; contract uuid; conv uuid; pay uuid; prod_id uuid; denied boolean;
 path_x text;path_y text;file_x uuid;file_y uuid;round_id uuid;remainder uuid;final_x uuid;final_y uuid;upload_input jsonb;
begin
 update staff_dispatch_settings set enabled=false where id;
 update creator_team_settings set enabled=true where id;
 insert into auth.users(id,email,raw_user_meta_data) values(aa,aa||'@example.invalid','{"full_name":"Team admin"}'),(ca,ca||'@example.invalid','{"full_name":"Team customer"}'),(sa,sa||'@example.invalid','{"full_name":"Team staff"}'),(sb,sb||'@example.invalid','{"full_name":"Team second staff"}'),(xa,xa||'@example.invalid','{"full_name":"Team creator one"}'),(ya,ya||'@example.invalid','{"full_name":"Team creator two"}'),(za,za||'@example.invalid','{"full_name":"Team expiry creator"}');
 select id into a from profiles where auth_user_id=aa; select id into c from profiles where auth_user_id=ca;
 select id into s from profiles where auth_user_id=sa; select id into s2 from profiles where auth_user_id=sb;
 select id into x from profiles where auth_user_id=xa; select id into y from profiles where auth_user_id=ya; select id into z from profiles where auth_user_id=za;
 update profiles set role='ADMIN' where id=a; update profiles set role='STAFF' where id in (s,s2);
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Team Video','Video','AVAILABLE') returning id into cx;
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Team Photo','Photo','AVAILABLE') returning id into cy;
 denied:=false; begin perform onboard_creator(s,cx,x,jsonb_build_object('agreement_reference','TEST-CONTRACT','signed_at',now())); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Staff grants Creator accounts'; end if;
 denied:=false; begin perform manage_user(a,x,'CREATOR',true); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Creator granted without company agreement'; end if;
 perform onboard_creator(a,cx,x,jsonb_build_object('agreement_reference','TEST-CONTRACT-X','signed_at',now()));
 perform onboard_creator(a,cy,y,jsonb_build_object('agreement_reference','TEST-CONTRACT-Y','signed_at',now()));
 if (select role from profiles where id=x)<>'CREATOR' then raise exception 'Onboarding did not grant canonical role'; end if;
 denied:=false; begin perform onboard_creator(a,cx,y,jsonb_build_object('agreement_reference','TEST-CONTRACT-X','signed_at',now())); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Onboarding steals a linked identity'; end if;
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Expiry Creator','Video','AVAILABLE') returning id into cz;
 perform onboard_creator(a,cz,z,jsonb_build_object('agreement_reference','TEST-CONTRACT-Z','signed_at',now()));
 insert into services(name,slug,active) values('Team service',gen_random_uuid()::text,true) returning id into svc;
 rid:=(request_action(c,null,'create',jsonb_build_object('service_id',svc,'title','Team request','brief','Test only','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform request_action(s,rid,'claim','{}'); perform request_action(s,rid,'status','{"status":"CONSULTING"}');
 select id into conv from conversations where request_id=rid;
 perform request_action(c,rid,'message','{"content":"Private negotiation before signing"}');
 if service_chat_scope(x,rid) is not null then raise exception 'Creator opens chat before assignment/contract';end if;
 px:=(request_commerce_action(s,rid,'propose',jsonb_build_object('creator_id',cx,'reason','Video scope'))->>'id')::uuid;
 perform creator_team_action(c,rid,'select',jsonb_build_object('proposal_id',px));
 -- Staff may add another candidate while preparing the team, before a quote exists.
 py:=(request_commerce_action(s,rid,'propose',jsonb_build_object('creator_id',cy,'reason','Photo scope'))->>'id')::uuid;
 perform creator_team_action(c,rid,'select',jsonb_build_object('proposal_id',py));
 if (select count(*) from request_creator_selections where request_id=rid)<>2 then raise exception 'Multiple Creator selection lost'; end if;
 denied:=false; begin perform creator_team_action(s,rid,'select',jsonb_build_object('proposal_id',py)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Staff impersonates customer team selection'; end if;
 denied:=false; begin perform creator_team_action(s,rid,'invite',jsonb_build_object('proposal_id',px,'deadline',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'work_scope','Video','response_minutes',16)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Reservation exceeds 15 minutes'; end if;
 ax:=(creator_team_action(s,rid,'invite',jsonb_build_object('proposal_id',px,'deadline',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'work_scope','Video','response_minutes',5))->>'id')::uuid;
 ay:=(creator_team_action(s,rid,'invite',jsonb_build_object('proposal_id',py,'deadline',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'work_scope','Photo','response_minutes',15))->>'id')::uuid;
 denied:=false; begin perform creator_team_action(s,rid,'accept',jsonb_build_object('assignment_id',ax)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Staff confirms Creator assignment'; end if;
 perform creator_team_action(x,rid,'accept',jsonb_build_object('assignment_id',ax));
 if creator_team_action(x,rid,'accept',jsonb_build_object('assignment_id',ax))->>'id'<>ax::text then raise exception 'Accept is not idempotent'; end if;
 denied:=false; begin perform request_commerce_action(s,rid,'quote_save',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('service_id',svc,'description','Team work','quantity',1,'unit_price',1000)),'valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+10,'revision_policy','Agreed scope','deposit_percent',30)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Quote bypasses second Creator confirmation'; end if;
 perform set_config('request.jwt.claim.sub',xa::text,true); execute 'set local role authenticated';
 if exists(select 1 from conversations where id=conv) or exists(select 1 from conversation_messages where conversation_id=conv) then raise exception 'Creator chat opens before customer contract'; end if;
 execute 'reset role';
 perform creator_team_action(y,rid,'accept',jsonb_build_object('assignment_id',ay));
 q:=(request_commerce_action(s,rid,'quote_save',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('service_id',svc,'description','Team work','quantity',1,'unit_price',1000)),'valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+10,'revision_policy','Agreed scope','deposit_percent',30))->>'id')::uuid;
 if jsonb_array_length((select team_snapshot from quotations where id=q))<>2 then raise exception 'Quote did not retain full team'; end if;
 perform request_commerce_action(s,rid,'quote_send',jsonb_build_object('quote_id',q));
 denied:=false; begin update quotations set team_snapshot='[]' where id=q; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Published team snapshot is mutable'; end if;
 oid:=(request_commerce_action(c,rid,'quote_accept',jsonb_build_object('quote_id',q))->>'order_id')::uuid;
 if jsonb_array_length((select team_snapshot from orders where id=oid))<>2 then raise exception 'Order did not preserve team'; end if;
 contract:=(order_action(s,oid,'contract_save',jsonb_build_object('title','Test terms','content','Rollback only terms','valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+10))->>'id')::uuid;
 perform order_action(s,oid,'contract_send',jsonb_build_object('contract_id',contract));
 perform order_action(c,oid,'contract_acknowledge',jsonb_build_object('contract_id',contract,'content_hash',(select content_hash from order_contracts where id=contract),'acknowledge',true));
 if jsonb_array_length((select team_snapshot from order_contracts where id=contract))<>2 or (select count(*) from conversations where request_id=rid)<>1 then raise exception 'Contract roster or single conversation failed'; end if;
 perform request_action(c,rid,'message','{"content":"Private financial follow-up","audience":"CUSTOMER_STAFF"}');
 if exists(select 1 from notifications where user_id=x and message='Private financial follow-up') then raise exception 'Private text leaked in Creator notification'; end if;
 if (select last_message_preview from conversations where id=conv) like '%financial%' then raise exception 'Private preview leaked'; end if;
 perform request_action(x,rid,'message','{"content":"Shared team update"}');
 denied:=false; begin perform request_action(x,rid,'message','{"content":"Impersonate private","audience":"CUSTOMER_STAFF"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Creator writes private commercial channel'; end if;
 perform set_config('request.jwt.claim.sub',xa::text,true); execute 'set local role authenticated';
 if not exists(select 1 from conversation_messages where conversation_id=conv and content='Shared team update') or exists(select 1 from conversation_messages where conversation_id=conv and (audience='CUSTOMER_STAFF' or kind in ('QUOTE','CONTRACT','PAYMENT'))) then raise exception 'Creator message RLS leaks private history or hides shared messages'; end if;
 if exists(select 1 from quotations where id=q) or exists(select 1 from order_contracts where id=contract) or exists(select 1 from orders where id=oid) then raise exception 'Creator can read customer finances'; end if;
 execute 'reset role';
 update profiles set active=false where id=x;
 perform set_config('request.jwt.claim.sub',xa::text,true); execute 'set local role authenticated';
 if exists(select 1 from conversation_messages where conversation_id=conv) then raise exception 'Suspended Creator retains chat access'; end if;
 execute 'reset role'; update profiles set active=true where id=x;
 r2:=(request_action(c,null,'create',jsonb_build_object('service_id',svc,'title','Other team','brief','Test only','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform request_action(s2,r2,'claim','{}'); perform request_action(s2,r2,'status','{"status":"CONSULTING"}');
 p2:=(request_commerce_action(s2,r2,'propose',jsonb_build_object('creator_id',cx,'reason','Other project'))->>'id')::uuid;
 perform creator_team_action(c,r2,'select',jsonb_build_object('proposal_id',p2));
 denied:=false; begin perform creator_team_action(s2,r2,'invite',jsonb_build_object('proposal_id',p2,'deadline',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'work_scope','Another video')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Creator accepted on two active projects'; end if;
 if (select status from creator_assignments where id=ax)<>'ACCEPTED' then raise exception 'Original reservation released too early'; end if;
 pz:=(request_commerce_action(s2,r2,'propose',jsonb_build_object('creator_id',cz,'reason','Expiry test'))->>'id')::uuid;
 perform creator_team_action(c,r2,'select',jsonb_build_object('proposal_id',pz));
 az:=(creator_team_action(s2,r2,'invite',jsonb_build_object('proposal_id',pz,'work_scope','Expiry scope','deadline',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'response_minutes',5))->>'id')::uuid;
 update creator_assignments set invited_at=clock_timestamp()-interval '10 minutes',expires_at=clock_timestamp()-interval '1 minute' where id=az;
 denied:=false; begin perform creator_team_action(z,r2,'accept',jsonb_build_object('assignment_id',az)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Expired reservation accepted'; end if;
 perform creator_team_action(s2,r2,'invite',jsonb_build_object('proposal_id',pz,'work_scope','Expiry scope','deadline',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'response_minutes',5));
 perform creator_team_action(z,r2,'decline',jsonb_build_object('assignment_id',az,'reason','Cannot meet deadline'));
 if (select status from creator_assignments where id=az)<>'DECLINED' then raise exception 'Creator refusal did not release reservation'; end if;
 if not exists(select 1 from audit_logs where entity_id=az and new_value->>'response_note'='Cannot meet deadline') then raise exception 'Assignment response history was lost'; end if;
 perform creator_team_action(s2,r2,'invite',jsonb_build_object('proposal_id',pz,'work_scope','Expiry scope','deadline',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'response_minutes',5));
 perform request_action(c,r2,'cancel','{"reason":"Withdraw an unclosed consultation only"}');
 if (select status from creator_assignments where id=az)<>'RELEASED' or (select status from creator_assignments where id=ax)<>'ACCEPTED' then raise exception 'Cancelling an unclosed request did not release only its own reservation'; end if;
 update payment_settings set enabled=true,bank_name='ROLLBACK BANK',account_number=gen_random_uuid()::text,account_name='QA ONLY' where id='default';
 pay:=(order_payment_action(s,oid,'create',jsonb_build_object('kind','DEPOSIT','due_date',(now() at time zone 'Asia/Ho_Chi_Minh')::date+10,'idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform order_payment_action(c,oid,'report',jsonb_build_object('payment_id',pay,'transfer_note','ROLLBACK ONLY'));
 perform order_payment_action(a,oid,'confirm',jsonb_build_object('payment_id',pay,'verified',true,'received_amount',300,'bank_transaction_reference',gen_random_uuid(),'received_at',now(),'reason','ROLLBACK ONLY'));
 perform set_config('request.jwt.claim.sub',xa::text,true); execute 'set local role authenticated';
 if exists(select 1 from conversation_messages where conversation_id=conv and (event_data->>'event') like 'PAYMENT_%') then raise exception 'Financial SYSTEM events leaked to Creator'; end if;
 execute 'reset role';
 prod_id:=(order_production_action(s,oid,'create','{}')->>'id')::uuid;
 if (select count(*) from project_team_members tm where tm.project_id=prod_id)<>2 then raise exception 'Production does not contain the whole team'; end if;
 perform order_production_action(s,oid,'milestone_save',jsonb_build_object('title','Test milestone','description','Test only','due_date',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'display_order',0,'idempotency_key',gen_random_uuid()));
 perform order_production_action(s,oid,'status','{"status":"READY","reason":"Rollback only"}');
 perform order_production_action(s,oid,'status','{"status":"IN_PROGRESS","reason":"Rollback only"}');
 perform creator_team_action(x,rid,'progress',jsonb_build_object('assignment_id',ax,'progress',100,'content','Reported externally; stored progress'));
 if (select status from creator_assignments where id=ax)<>'ACCEPTED' or not exists(select 1 from creator_progress_updates where assignment_id=ax and progress=100) then raise exception '100 percent progress freed Creator or failed to persist'; end if;
 denied:=false; begin perform creator_team_action(y,rid,'progress',jsonb_build_object('assignment_id',ax,'progress',100,'content','Other Creator progress')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Creator updates another assignment'; end if;
 if has_function_privilege('authenticated','creator_team_action(uuid,uuid,text,jsonb)','EXECUTE') or has_function_privilege('service_role','legacy_request_action_027(uuid,uuid,text,jsonb)','EXECUTE') or has_table_privilege('authenticated','creator_assignments','UPDATE') then raise exception 'Untrusted direct Creator assignment access'; end if;
 -- Multi-Creator review/final delivery retains the same workspace and only
 -- releases the entire team after every accepted file has a final version.
 path_x:=oid::text||'/'||gen_random_uuid()::text||'.pdf';path_y:=oid::text||'/'||gen_random_uuid()::text||'.pdf';
 insert into storage.objects(bucket_id,name,metadata) values('order-deliverables',path_x,'{"size":100,"mimetype":"application/pdf"}'),('order-deliverables',path_y,'{"size":100,"mimetype":"application/pdf"}');
 upload_input:=jsonb_build_object('assignment_id',ax,'kind','REVIEW','title','Video review','confirmed',true,'file_name','review.pdf','path',path_x,'type','application/pdf','size',100);
 denied:=false;begin perform order_delivery_action(y,oid,'upload',upload_input);exception when raise_exception then denied:=true;end;if not denied then raise exception 'Creator uploads other assignment';end if;
 denied:=false;begin perform order_delivery_action(x,oid,'upload',upload_input||'{"confirmed":false}');exception when raise_exception then denied:=true;end;if not denied then raise exception 'Review lacks watermark declaration';end if;
 file_x:=(order_delivery_action(x,oid,'upload',upload_input)->>'submission_id')::uuid;
 file_y:=(order_delivery_action(y,oid,'upload',upload_input||jsonb_build_object('assignment_id',ay,'title','Photo review','path',path_y))->>'submission_id')::uuid;
 denied:=false;begin perform order_delivery_action(s,oid,'send_review',jsonb_build_object('submission_ids',jsonb_build_array(file_x,file_y),'note','Mốc chưa hoàn thành'));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Review skips incomplete milestones';end if;
 perform order_production_action(s,oid,'milestone_status',jsonb_build_object('milestone_id',(select id from project_milestones where project_id=prod_id limit 1),'status','IN_PROGRESS','reason','Review test'));
 perform order_production_action(s,oid,'milestone_status',jsonb_build_object('milestone_id',(select id from project_milestones where project_id=prod_id limit 1),'status','COMPLETED','reason','Review test completed'));
 denied:=false;begin perform order_delivery_action(s,oid,'send_review',jsonb_build_object('submission_ids',jsonb_build_array(file_x),'note','Missing team member'));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Review omits a Creator';end if;
 round_id:=(order_delivery_action(s,oid,'send_review',jsonb_build_object('submission_ids',jsonb_build_array(file_x,file_y),'note','Review full team'))->>'round_id')::uuid;
 denied:=false;begin perform order_delivery_action(a,oid,'accept_review',jsonb_build_object('round_id',round_id,'confirmed',true));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Admin impersonates customer review acceptance';end if;
 perform order_delivery_action(c,oid,'request_revision',jsonb_build_object('round_id',round_id,'note','Change typography within agreed scope'));
 if (select production_status from projects where id=prod_id)<>'REVISION' then raise exception 'Customer revision not recorded';end if;
 round_id:=(order_delivery_action(s,oid,'send_review',jsonb_build_object('submission_ids',jsonb_build_array(file_x,file_y),'note','Reviewed agreed scope again'))->>'round_id')::uuid;
 perform order_delivery_action(c,oid,'accept_review',jsonb_build_object('round_id',round_id,'confirmed',true));
 perform order_delivery_action(c,oid,'accept_review',jsonb_build_object('round_id',round_id,'confirmed',true));
 perform pg_temp.verify_service_chat(a,c,s,x,rid,conv);
 if (select count(*) from order_review_rounds where order_id=oid)<>2 or (select status from orders where id=oid)<>'WAITING_ACCEPTANCE' then raise exception 'Review history/acceptance missing';end if;
 path_x:=oid::text||'/'||gen_random_uuid()::text||'.pdf';path_y:=oid::text||'/'||gen_random_uuid()::text||'.pdf';
 insert into storage.objects(bucket_id,name,metadata) values('order-deliverables',path_x,'{"size":100,"mimetype":"application/pdf"}'),('order-deliverables',path_y,'{"size":100,"mimetype":"application/pdf"}');
 upload_input:=jsonb_build_object('assignment_id',ax,'kind','FINAL','final_of',file_x,'title','Final video','confirmed',true,'file_name','final.pdf','path',path_x,'type','application/pdf','size',100);
 denied:=false;begin perform order_delivery_action(x,oid,'upload',upload_input);exception when raise_exception then denied:=true;end;if not denied then raise exception 'Final released before full funds';end if;
 remainder:=(order_payment_action(s,oid,'create',jsonb_build_object('kind','REMAINING','due_date',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform order_payment_action(c,oid,'report',jsonb_build_object('payment_id',remainder,'transfer_note','Synthetic remainder'));
 perform order_payment_action(s,oid,'confirm',jsonb_build_object('payment_id',remainder,'verified',true,'received_amount',700,'bank_transaction_reference',gen_random_uuid(),'received_at',now(),'reason','Actual evidence rollback only'));
 denied:=false;begin perform order_delivery_action(x,oid,'upload',upload_input);exception when raise_exception then denied:=true;end;if not denied then raise exception 'Final released without Staff full-funds confirmation';end if;
 perform confirm_order_final_funds(s,oid,'{"verified":true,"note":"Full funds checked rollback only"}');
 final_x:=(order_delivery_action(x,oid,'upload',upload_input)->>'submission_id')::uuid;
 if (select status from orders where id=oid)='COMPLETED' or (select status from creator_assignments where id=ax)<>'ACCEPTED' then raise exception 'Partial final delivery completes project/frees Creator';end if;
 denied:=false;begin perform order_feedback_action(c,oid,'review',jsonb_build_object('show_name',false,'notice_version','EXCERPT_V1','rating',5,'content','Too soon','creators','[]'::jsonb));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Feedback opens before full-team final delivery';end if;
 final_y:=(order_delivery_action(y,oid,'upload',upload_input||jsonb_build_object('assignment_id',ay,'final_of',file_y,'title','Final photo','path',path_y))->>'submission_id')::uuid;
 if (select status from orders where id=oid)<>'COMPLETED' or (select production_status from projects where id=prod_id)<>'COMPLETED' or (select count(*) from creator_assignments where request_id=rid and status='COMPLETED')<>2 then raise exception 'Complete team delivery did not finish/release whole project';end if;
 perform pg_temp.verify_completed_feedback(a,c,s,x,oid,cx,cy);
 if service_chat_scope(x,rid)->>'closed'<>'true' then raise exception 'Completed chat remains writable';end if;
 denied:=false;begin perform request_action(s,rid,'message','{"content":"After completion"}');exception when raise_exception then denied:=true;end;if not denied then raise exception 'Message posted after full-team completion';end if;
 if (select count(*) from conversations where request_id=rid)<>1 then raise exception 'Delivery forks service conversation';end if;
 denied:=false;begin update production_submissions set storage_path='other' where id=final_x;exception when raise_exception then denied:=true;end;if not denied then raise exception 'Final evidence is mutable';end if;
 perform set_config('request.jwt.claim.sub',xa::text,true);execute 'set local role authenticated';
 if (select count(*) from production_submissions where order_id=oid)<>4 or (select count(*) from order_review_rounds where order_id=oid)<>2 then raise exception 'Creator cannot read shared delivery evidence';end if;
 if exists(select 1 from storage.objects where bucket_id='order-deliverables') then raise exception 'Client bypasses signed download through storage';end if;
 execute 'reset role';
 if has_function_privilege('authenticated','order_delivery_action(uuid,uuid,text,jsonb)','execute') or has_function_privilege('authenticated','is_delivery_reader(uuid,uuid)','execute') or has_table_privilege('authenticated','production_submissions','insert') then raise exception 'Untrusted delivery write/bypass exposed';end if;
end $$;
