-- All actors, payment requests and MANUAL_BANK receipts below are rolled back.
do $$
declare aa uuid:=gen_random_uuid(); ca uuid:=gen_random_uuid(); sa uuid:=gen_random_uuid(); na uuid:=gen_random_uuid(); xa uuid:=gen_random_uuid();
 admin_id uuid; owner_id uuid; staff_id uuid; next_id uuid; other_id uuid; service_id uuid; creator_id uuid;
 rid uuid; oid uuid; proposal_id uuid; qid uuid; cid uuid; pid uuid; mid uuid; eid uuid; remainder uuid; full_id uuid; idem uuid:=gen_random_uuid();
 input jsonb; confirm_input jsonb; bank_copy jsonb; denied boolean; legacy_plans bigint; legacy_receipts bigint; project_count bigint; invoice_count bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data) values
 (aa,aa||'@example.invalid','{"full_name":"Payment admin"}'),(ca,ca||'@example.invalid','{"full_name":"Payment business"}'),
 (sa,sa||'@example.invalid','{"full_name":"Payment staff"}'),(na,na||'@example.invalid','{"full_name":"Payment transfer"}'),(xa,xa||'@example.invalid','{"full_name":"Payment other"}');
 select id into admin_id from profiles where auth_user_id=aa; select id into owner_id from profiles where auth_user_id=ca;
 select id into staff_id from profiles where auth_user_id=sa; select id into next_id from profiles where auth_user_id=na; select id into other_id from profiles where auth_user_id=xa;
 update profiles set role='ADMIN' where id=admin_id; update profiles set role='BUSINESS' where id=owner_id; update profiles set role='STAFF' where id in (staff_id,next_id);
 insert into services(name,slug,active) values('Payment service',gen_random_uuid()::text,true) returning id into service_id;
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Payment creator','Video','AVAILABLE') returning id into creator_id;
 select count(*) into legacy_plans from payment_plans; select count(*) into legacy_receipts from payment_installments;
 select count(*) into project_count from projects; select count(*) into invoice_count from invoices;
 update payment_settings set enabled=true,bank_name='ROLLBACK TEST BANK',account_number=gen_random_uuid()::text,account_name='ROLLBACK ONLY',instructions='No actual payment' where id='default';
 rid:=(request_action(owner_id,null,'create',jsonb_build_object('service_id',service_id,'title','Payment brief','brief','Rollback only','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform request_action(staff_id,rid,'claim','{}'); perform request_action(staff_id,rid,'status','{"status":"CONSULTING"}');
 proposal_id:=(request_commerce_action(staff_id,rid,'propose',jsonb_build_object('creator_id',creator_id,'reason','Test only'))->>'id')::uuid;
 perform request_commerce_action(owner_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_id));
 qid:=(request_commerce_action(staff_id,rid,'quote_save',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('service_id',service_id,'description','Video','quantity',1,'unit_price',1000)),'valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14,'revision_policy','Two rounds','deposit_percent',30))->>'id')::uuid;
 perform request_commerce_action(staff_id,rid,'quote_send',jsonb_build_object('quote_id',qid));
 oid:=(request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',qid))->>'order_id')::uuid;
 input:=jsonb_build_object('kind','DEPOSIT','due_date',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14,'note','QA only','idempotency_key',idem);
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Payment requested before acknowledgment'; end if;
 cid:=(order_action(staff_id,oid,'contract_save',jsonb_build_object('title','Payment terms','content','Rollback only','valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14))->>'id')::uuid;
 perform order_action(staff_id,oid,'contract_send',jsonb_build_object('contract_id',cid));
 perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',cid,'content_hash',(select content_hash from order_contracts where id=cid),'acknowledge',true));
 denied:=false; begin perform order_payment_action(owner_id,oid,'create',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Customer creates collection request'; end if;
 denied:=false; begin perform order_payment_action(other_id,oid,'create',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Unrelated customer accesses payment'; end if;
 update payment_settings set enabled=false where id='default';
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Disabled bank permits payment request'; end if;
 update payment_settings set enabled=true where id='default';
 full_id:=(order_payment_action(staff_id,oid,'create',input||jsonb_build_object('kind','FULL','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 if (select amount from order_payment_requests where id=full_id)<>1000 then raise exception 'Full payment does not use accepted order total'; end if;
 perform order_payment_action(staff_id,oid,'cancel',jsonb_build_object('payment_id',full_id,'reason','Choose deposit instead'));
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input||jsonb_build_object('due_date',(now() at time zone 'Asia/Ho_Chi_Minh')::date-1)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Past due date accepted at issuance'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input||'{"amount":1}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Forged deposit amount accepted'; end if;
 pid:=(order_payment_action(staff_id,oid,'create',input)->>'id')::uuid;
 if order_payment_action(staff_id,oid,'create',input)->>'id'<>pid::text or (select amount from order_payment_requests where id=pid)<>300 then raise exception 'Deposit/idempotency not based on accepted order'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input||'{"note":"Different input"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Idempotency key reuses changed terms'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input||jsonb_build_object('kind','FULL','idempotency_key',gen_random_uuid())); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Full request overlaps active deposit'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input||jsonb_build_object('kind','MILESTONE','amount',701,'idempotency_key',gen_random_uuid())); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Requests reserve more than outstanding total'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'create',input||jsonb_build_object('kind','MILESTONE','amount',1.001,'idempotency_key',gen_random_uuid())); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Payment accepts excess precision'; end if;
 mid:=(order_payment_action(staff_id,oid,'create',input||jsonb_build_object('kind','MILESTONE','percentage',20,'idempotency_key',gen_random_uuid()))->>'id')::uuid;
 if (select amount from order_payment_requests where id=mid)<>200 then raise exception 'Milestone percentage not server-calculated'; end if;
 bank_copy:=(select bank_snapshot from order_payment_requests where id=pid);
 update payment_settings set bank_name='Changed setting' where id='default';
 if (select bank_snapshot from order_payment_requests where id=pid) is distinct from bank_copy then raise exception 'Payment bank snapshot changes retroactively'; end if;
 denied:=false; begin update order_payment_requests set amount=1 where id=pid; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Issued amount is mutable'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'report',jsonb_build_object('payment_id',pid,'transfer_note','Impersonation')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Staff impersonates customer transfer'; end if;
 perform order_payment_action(owner_id,oid,'report',jsonb_build_object('payment_id',pid,'transfer_note','Rollback only transfer report'));
 perform order_payment_action(owner_id,oid,'report',jsonb_build_object('payment_id',pid,'transfer_note','Rollback only transfer report'));
 if (select status from orders where id=oid)<>'WAITING_PAYMENT' or exists(select 1 from order_payment_receipts where order_id=oid) then raise exception 'Customer report became receipt/confirmed order'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'cancel',jsonb_build_object('payment_id',pid,'reason','Hide pending receipt')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Operator cancels reported payment before reconciliation'; end if;
 confirm_input:=jsonb_build_object('payment_id',pid,'verified',true,'received_amount',300,'bank_transaction_reference',' qa-bank-1 ','received_at',now(),'reason','Private bank reconciliation note');
 denied:=false; begin perform order_payment_action(staff_id,oid,'confirm',confirm_input||'{"verified":false}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Staff confirms receipt without explicit actual-evidence acknowledgment'; end if;
 denied:=false; begin perform order_payment_action(admin_id,oid,'confirm',confirm_input||'{"received_amount":1}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Mismatched receipt amount accepted'; end if;
 denied:=false; begin perform order_payment_action(admin_id,oid,'confirm',confirm_input||jsonb_build_object('received_at',now()+interval '1 hour')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Future receipt accepted'; end if;
 perform order_payment_action(admin_id,oid,'reject',jsonb_build_object('payment_id',pid,'reason','No receipt found; please clarify'));
 if (select status from order_payment_requests where id=pid)<>'PENDING' then raise exception 'Reject failed to return pending request'; end if;
 perform order_payment_action(owner_id,oid,'report',jsonb_build_object('payment_id',pid,'transfer_note','Rechecked rollback report'));
 perform order_payment_action(admin_id,oid,'confirm',confirm_input);
 perform order_payment_action(admin_id,oid,'confirm',confirm_input);
 if (select count(*) from order_payment_receipts where order_id=oid)<>1 or (select status from orders where id=oid)<>'CONFIRMED' then raise exception 'Deposit receipt duplicates or fails order gate'; end if;
 if (select amount from order_payment_receipts where payment_request_id=pid)<>300 or (select bank_transaction_reference from order_payment_receipts where payment_request_id=pid)<>'QA-BANK-1' or (select verification_method from order_payment_receipts where payment_request_id=pid)<>'MANUAL_BANK' then raise exception 'Verified receipt evidence invalid'; end if;
 denied:=false; begin update order_payment_receipts set amount=1 where payment_request_id=pid; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Verified receipt mutable'; end if;
 denied:=false; begin delete from order_payment_receipts where payment_request_id=pid; exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Verified receipt deletable'; end if;
 -- The same bank transaction must not pay a second request.
 perform order_payment_action(owner_id,oid,'report',jsonb_build_object('payment_id',mid,'transfer_note','Rollback milestone'));
 -- Restore the same receiving bank as the deposit to exercise the global unique key.
 -- mid was issued before the settings change and preserves that bank snapshot.
 denied:=false; begin perform order_payment_action(admin_id,oid,'confirm',confirm_input||jsonb_build_object('payment_id',mid,'received_amount',200)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Duplicate bank transaction pays two requests'; end if;
 perform order_payment_action(admin_id,oid,'reject',jsonb_build_object('payment_id',mid,'reason','Duplicate transfer reference'));
 perform order_payment_action(staff_id,oid,'cancel',jsonb_build_object('payment_id',mid,'reason','Replace with remaining payment'));
 -- Insert an elapsed request as a trusted rollback fixture; public workflow cannot edit due dates.
 insert into order_payment_requests(order_id,kind,amount,due_date,bank_snapshot,created_by,idempotency_key,request_input)
 values(oid,'MILESTONE',50,(now() at time zone 'Asia/Ho_Chi_Minh')::date-1,bank_copy,staff_id,gen_random_uuid(),'{}') returning id into eid;
 denied:=false; begin perform order_payment_action(owner_id,oid,'report',jsonb_build_object('payment_id',eid,'transfer_note','Too late')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Expired due date permits customer report'; end if;
 perform order_payment_action(staff_id,oid,'expire',jsonb_build_object('payment_id',eid));
 remainder:=(order_payment_action(staff_id,oid,'create',input||jsonb_build_object('kind','REMAINING','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 if (select amount from order_payment_requests where id=remainder)<>700 then raise exception 'Remaining not based on verified receipts'; end if;
 denied:=false; begin perform order_payment_action(staff_id,oid,'expire',jsonb_build_object('payment_id',remainder)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Unexpired payment can expire'; end if;
 perform order_action(staff_id,oid,'assign',jsonb_build_object('assigned_to',next_id,'reason','Private financial transfer reason'));
 denied:=false; begin perform order_payment_action(staff_id,oid,'cancel',jsonb_build_object('payment_id',remainder,'reason','Old staff')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Transferred staff accesses payments'; end if;
 perform set_config('request.jwt.claim.sub',sa::text,true); execute 'set local role authenticated';
 if exists(select 1 from order_payment_requests where order_id=oid) or exists(select 1 from order_payment_receipts where order_id=oid) then raise exception 'Prior staff payment RLS persists'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',xa::text,true); execute 'set local role authenticated';
 if exists(select 1 from order_payment_requests where order_id=oid) or exists(select 1 from order_payment_receipts where order_id=oid) then raise exception 'Other customer reads payment history'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',ca::text,true); execute 'set local role authenticated';
 if (select count(*) from order_payment_requests where order_id=oid)<>5 or (select count(*) from order_payment_receipts where order_id=oid)<>1 then raise exception 'Owner cannot read payment/receipt evidence'; end if;
 execute 'reset role';
 perform order_payment_action(owner_id,oid,'report',jsonb_build_object('payment_id',remainder,'transfer_note','Rollback final payment'));
 perform order_payment_action(admin_id,oid,'confirm',confirm_input||jsonb_build_object('payment_id',remainder,'received_amount',700,'bank_transaction_reference','QA-BANK-2'));
 if (select sum(amount) from order_payment_receipts where order_id=oid)<>1000 then raise exception 'Collected totals inconsistent'; end if;
 denied:=false; begin perform order_payment_action(next_id,oid,'create',input||jsonb_build_object('kind','REMAINING','idempotency_key',gen_random_uuid())); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Fully paid order accepts another request'; end if;
 if (select count(*) from projects)<>project_count or (select count(*) from invoices)<>invoice_count or (select count(*) from payment_plans)<>legacy_plans or (select count(*) from payment_installments)<>legacy_receipts then raise exception 'New payment rewrites legacy/creates premature production'; end if;
 if exists(select 1 from conversation_messages where conversation_id=(select id from conversations where request_id=rid) and content like '%Private bank reconciliation note%') then raise exception 'Private reconciliation note enters shared conversation'; end if;
 if not exists(select 1 from conversation_messages where conversation_id=(select id from conversations where request_id=rid) and kind='PAYMENT' and event_data->>'order_id'=oid::text) or not exists(select 1 from audit_logs where action='PAYMENT_VERIFIED' and entity_id=rid and reason='Private bank reconciliation note') then raise exception 'Payment card/audit missing'; end if;
 if has_function_privilege('authenticated','order_payment_action(uuid,uuid,text,jsonb)','execute') or has_table_privilege('authenticated','order_payment_receipts','insert') then raise exception 'Client can forge receipt'; end if;
end $$;
