import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
process.env.NODE_ENV='test';process.env.SUPABASE_URL='http://127.0.0.1:59999';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';
const {app,apiLimiter}=await import('../dist/app.mjs');const {db}=await import('../dist/db.js');
const pid='11111111-1111-4111-8111-111111111111',oid='22222222-2222-4222-8222-222222222222',vid='33333333-3333-4333-8333-333333333333',qid='44444444-4444-4444-8444-444444444444';
let server,base;before(async()=>{server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}/api/order-variations`;});after(()=>new Promise(resolve=>server.close(resolve)));
const headers={Authorization:'Bearer test-only','Content-Type':'application/json'},post=(path,body)=>fetch(base+path,{method:'POST',headers,body:JSON.stringify(body)});
async function identity(role,run,{allowed=true,rpcError=null,active=true}={}){
 apiLimiter.resetKey('127.0.0.1');const old={from:db.from,rpc:db.rpc,getUser:db.auth.getUser},calls=[];
 db.auth.getUser=async()=>({data:{user:{id:pid}},error:null});
 db.from=table=>{let rows=table==='profiles'?[{id:pid,auth_user_id:pid,role,active,full_name:'Test',email:'qa@example.invalid'}]:table==='customers'?[{id:oid,profile_id:pid}]:[];return{select(){return this},eq(field,value){rows=rows.filter(row=>row[field]===value);return this},maybeSingle:async()=>({data:rows[0]||null,error:null})}};
 db.rpc=async(name,args)=>{calls.push({name,args});return{data:name==='order_variation_scopes'?(allowed?{items:[{id:vid,title:'Cut',scope:'Extra cut',revision_policy:'Two minor changes',deadline:'2026-12-31'}],page:args.report_page,total:1,limit:10}:null):name==='order_variation_list'?(allowed?{items:[],can_request:true}:null):{id:vid,quote_id:qid},error:name==='order_variation_action'?rpcError:null}};
 try{await run(calls)}finally{db.from=old.from;db.rpc=old.rpc;db.auth.getUser=old.getUser}
}
const request={title:'Extra cut',description:'Please add one cut',idempotency_key:vid},accept={variation_id:vid,quote_id:qid,content_hash:'a'.repeat(64),acknowledge:true};
test('Variation resources require login',async()=>assert.equal((await fetch(base+'/'+oid)).status,401));
test('Creator cannot read commercial appendix or initiate it',async()=>identity('CREATOR',async calls=>{assert.equal((await fetch(base+'/'+oid,{headers})).status,403);assert.equal((await post('/'+oid+'/request',request)).status,403);assert.equal(calls.length,0)}));
test('Creator scope uses separate safe projection and server identity',async()=>identity('CREATOR',async calls=>{const r=await fetch(base+'/'+oid+'/scope?page=2',{headers});assert.equal(r.status,200);const data=(await r.json()).data;assert.equal(Object.hasOwn(data.items[0],'amount'),false);assert.equal(Object.hasOwn(data.items[0],'content_hash'),false);assert.deepEqual(calls,[{name:'order_variation_scopes',args:{actor_id:pid,oid,report_page:2}}])}));
test('Another owner and unassigned Staff see no foreign appendix and cannot mutate',async()=>{for(const role of ['CUSTOMER','STAFF'])await identity(role,async calls=>{assert.equal((await fetch(base+'/'+oid,{headers})).status,404);assert.equal((await post('/'+oid+'/reject',{variation_id:vid,reason:'No'})).status,404);assert.equal(calls.some(c=>c.name==='order_variation_action'),false)},{allowed:false})});
test('Customer creates with fixed retry key and server actor',async()=>identity('CUSTOMER',async calls=>{assert.equal((await post('/'+oid+'/request',request)).status,200);assert.deepEqual(calls.at(-1),{name:'order_variation_action',args:{actor_id:pid,oid,operation:'request',payload:request}})}));
test('Staff cannot initiate customer request or accept on behalf',async()=>identity('STAFF',async calls=>{assert.equal((await post('/'+oid+'/request',request)).status,403);assert.equal((await post('/'+oid+'/accept',accept)).status,403);assert.equal(calls.length,0)}));
test('Customer cannot publish a variation quote',async()=>identity('CUSTOMER',async calls=>{assert.equal((await post('/'+oid+'/quote',{})).status,403);assert.equal(calls.length,0)}));
test('Customer acknowledgment binds version and checked terms',async()=>identity('CUSTOMER',async calls=>{assert.equal((await post('/'+oid+'/accept',{...accept,acknowledge:false})).status,422);assert.equal((await post('/'+oid+'/accept',{...accept,content_hash:'forged'})).status,422);assert.equal(calls.length,0);assert.equal((await post('/'+oid+'/accept',accept)).status,200);assert.deepEqual(calls.at(-1).args.payload,accept)}));
test('Reject actor spoofing, raw financial changes and unknown query keys',async()=>identity('ADMIN',async calls=>{assert.equal((await post('/'+oid+'/reject',{variation_id:vid,reason:'No',actor_id:vid})).status,422);assert.equal((await fetch(base+'/'+oid+'?actor_id='+vid,{headers})).status,422);assert.equal((await fetch(base+'/'+oid+'?page=0',{headers})).status,422);assert.equal(calls.length,0)}));
test('Strict Staff quote rejects fractional cents and missing scope',async()=>identity('STAFF',async calls=>{const input={variation_id:vid,idempotency_key:qid,scope:'One cut',revision_policy:'Two minor changes',amount:12.345,deadline:'2026-12-31',valid_until:'2026-12-01'};assert.equal((await post('/'+oid+'/quote',input)).status,422);assert.equal((await post('/'+oid+'/quote',{...input,amount:12.34,scope:' '})).status,422);assert.equal(calls.length,0);assert.equal((await post('/'+oid+'/quote',{...input,amount:12.34})).status,200)}));
test('Stale confirmation conflict remains visible without HTTP false success',async()=>identity('CUSTOMER',async()=>{const r=await post('/'+oid+'/accept',accept);assert.equal(r.status,409);assert.equal((await r.json()).error.code,'INVALID_WORKFLOW')},{rpcError:{code:'P0001',message:'Cần bản phụ lục mới nhất.'}}));
test('Inactive account cannot read safe or commercial scope',async()=>identity('CREATOR',async calls=>{assert.equal((await fetch(base+'/'+oid+'/scope',{headers})).status,403);assert.equal(calls.length,0)},{active:false}));

test('Focused appendix page remains bound to the verified order and validates target UUID',async()=>identity('CUSTOMER',async calls=>{assert.equal((await fetch(base+'/'+oid+'?focus_id='+vid,{headers})).status,200);assert.deepEqual(calls.at(-1).args,{actor_id:pid,oid,report_page:1,focus_id:vid});assert.equal((await fetch(base+'/'+oid+'?focus_id=foreign-query',{headers})).status,422)}));
