-- Rollback-only order production. No real receipt/project/creator booking.
do $$
declare aa uuid:=gen_random_uuid(); ca uuid:=gen_random_uuid(); sa uuid:=gen_random_uuid(); na uuid:=gen_random_uuid(); xa uuid:=gen_random_uuid();
 admin_id uuid; owner_id uuid; staff_id uuid; next_id uuid; other_id uuid; service_id uuid; creator_id uuid;
 rid uuid; oid uuid; proposal_id uuid; qid uuid; cid uuid; payid uuid; pid uuid; mid uuid; denied boolean; input jsonb; invoice_count bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data) values
 (aa,aa||'@example.invalid','{"full_name":"Production admin"}'),(ca,ca||'@example.invalid','{"full_name":"Production business"}'),
 (sa,sa||'@example.invalid','{"full_name":"Production staff"}'),(na,na||'@example.invalid','{"full_name":"Production transfer"}'),(xa,xa||'@example.invalid','{"full_name":"Production other"}');
 select id into admin_id from profiles where auth_user_id=aa; select id into owner_id from profiles where auth_user_id=ca;
 select id into staff_id from profiles where auth_user_id=sa; select id into next_id from profiles where auth_user_id=na; select id into other_id from profiles where auth_user_id=xa;
 update profiles set role='ADMIN' where id=admin_id; update profiles set role='BUSINESS' where id=owner_id; update profiles set role='STAFF' where id in (staff_id,next_id);
 insert into services(name,slug,active) values('Production service',gen_random_uuid()::text,true) returning id into service_id;
 insert into creator_profiles(slug,display_name,title,availability) values(gen_random_uuid()::text,'Production creator','Video','AVAILABLE') returning id into creator_id;
 select count(*) into invoice_count from invoices;
 update payment_settings set enabled=true,bank_name='ROLLBACK BANK',account_number=gen_random_uuid()::text,account_name='QA ONLY' where id='default';
 rid:=(request_action(owner_id,null,'create',jsonb_build_object('service_id',service_id,'title','Production brief','brief','Rollback only','idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform request_action(staff_id,rid,'claim','{}'); perform request_action(staff_id,rid,'status','{"status":"CONSULTING"}');
 proposal_id:=(request_commerce_action(staff_id,rid,'propose',jsonb_build_object('creator_id',creator_id,'reason','Test only'))->>'id')::uuid;
 perform request_commerce_action(owner_id,rid,'proposal_select',jsonb_build_object('proposal_id',proposal_id));
 qid:=(request_commerce_action(staff_id,rid,'quote_save',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('service_id',service_id,'description','Video','quantity',1,'unit_price',1000)),'valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14,'revision_policy','Two rounds','deposit_percent',30))->>'id')::uuid;
 perform request_commerce_action(staff_id,rid,'quote_send',jsonb_build_object('quote_id',qid));
 oid:=(request_commerce_action(owner_id,rid,'quote_accept',jsonb_build_object('quote_id',qid))->>'order_id')::uuid;
 denied:=false; begin perform order_production_action(staff_id,oid,'create','{}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Production created from quote alone'; end if;
 cid:=(order_action(staff_id,oid,'contract_save',jsonb_build_object('title','Terms','content','Rollback only','valid_until',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14))->>'id')::uuid;
 perform order_action(staff_id,oid,'contract_send',jsonb_build_object('contract_id',cid));
 perform order_action(owner_id,oid,'contract_acknowledge',jsonb_build_object('contract_id',cid,'content_hash',(select content_hash from order_contracts where id=cid),'acknowledge',true));
 payid:=(order_payment_action(staff_id,oid,'create',jsonb_build_object('kind','DEPOSIT','due_date',(now() at time zone 'Asia/Ho_Chi_Minh')::date+14,'idempotency_key',gen_random_uuid()))->>'id')::uuid;
 perform order_payment_action(owner_id,oid,'report',jsonb_build_object('payment_id',payid,'transfer_note','Rollback only'));
 denied:=false; begin perform order_production_action(staff_id,oid,'create','{}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Production created from unverified transfer'; end if;
 perform order_payment_action(admin_id,oid,'confirm',jsonb_build_object('payment_id',payid,'verified',true,'received_amount',300,'bank_transaction_reference',gen_random_uuid(),'received_at',now(),'reason','Rollback only'));
 denied:=false; begin perform order_production_action(owner_id,oid,'create','{}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Customer creates production'; end if;
 denied:=false; begin perform order_production_action(other_id,oid,'create','{}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Unrelated actor creates production'; end if;
 pid:=(order_production_action(staff_id,oid,'create','{}')->>'id')::uuid;
 if order_production_action(staff_id,oid,'create','{}')->>'id'<>pid::text or (select count(*) from projects where order_id=oid)<>1 then raise exception 'Production creation not idempotent'; end if;
 if (select customer_id from projects where id=pid)<>(select customer_id from orders where id=oid) or (select production_status from projects where id=pid)<>'PLANNING' or (select status from projects where id=pid)<>'DRAFT'
  or not exists(select 1 from project_team_members tm where tm.project_id=pid and tm.creator_id=(select o.creator_id from orders o where o.id=oid)) or not exists(select 1 from project_services ps where ps.project_id=pid and ps.service_id=(select req.service_id from requests req where req.id=rid)) then raise exception 'Production origin/snapshots invalid'; end if;
 denied:=false; begin perform project_action(owner_id,pid,'edit','{}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Legacy project RPC bypasses order gates'; end if;
 denied:=false; begin perform edit_project(admin_id,pid,jsonb_build_object('title','Bypass','description','Bypass','scope','','progress',100)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Legacy edit RPC changes order production'; end if;
 denied:=false; begin perform save_quotation(admin_id,pid,'{}',false); exception when raise_exception then denied:=true; end;
 -- The legacy quote RPC can reject before insertion because the legacy status is DRAFT.
 if not denied then raise exception 'Legacy quotation creates new commercial terms'; end if;
 denied:=false; begin perform order_production_action(staff_id,oid,'status','{"status":"COMPLETED","reason":"Skip delivery"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Production skips review/payment/acceptance'; end if;
 perform order_production_action(staff_id,oid,'status','{"status":"READY","reason":"Planning reviewed"}');
 denied:=false; begin perform order_production_action(staff_id,oid,'status','{"status":"IN_PROGRESS","reason":"Missing milestones"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Production starts without milestone'; end if;
 input:=jsonb_build_object('title','First cut','description','QA only','due_date',(now() at time zone 'Asia/Ho_Chi_Minh')::date+7,'display_order',1,'idempotency_key',gen_random_uuid());
 mid:=(order_production_action(staff_id,oid,'milestone_save',input)->>'milestone_id')::uuid;
 if order_production_action(staff_id,oid,'milestone_save',input)->>'milestone_id'<>mid::text then raise exception 'Milestone retry duplicates'; end if;
 denied:=false; begin perform order_production_action(staff_id,oid,'milestone_save',input||'{"title":"Changed intent"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Milestone changed intent shares key'; end if;
 perform order_production_action(staff_id,oid,'status','{"status":"IN_PROGRESS","reason":"Start planned work"}');
 if (select status from orders where id=oid)<>'IN_PROGRESS' then raise exception 'Order fails production status synchronization'; end if;
 denied:=false; begin perform order_production_action(staff_id,oid,'milestone_status',jsonb_build_object('milestone_id',mid,'status','COMPLETED','reason','Skip active')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Milestone skips active transition'; end if;
 perform order_production_action(staff_id,oid,'milestone_status',jsonb_build_object('milestone_id',mid,'status','IN_PROGRESS','reason','Work starts'));
 denied:=false; begin perform order_production_action(staff_id,oid,'milestone_save',input||jsonb_build_object('milestone_id',mid)); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Started milestone edited'; end if;
 perform order_production_action(staff_id,oid,'status','{"status":"ON_HOLD","reason":"Wait for customer material"}');
 denied:=false; begin perform order_production_action(staff_id,oid,'milestone_status',jsonb_build_object('milestone_id',mid,'status','COMPLETED','reason','Paused')); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Milestone advances while production on hold'; end if;
 perform order_production_action(staff_id,oid,'status','{"status":"IN_PROGRESS","reason":"Material received"}');
 perform order_production_action(staff_id,oid,'milestone_status',jsonb_build_object('milestone_id',mid,'status','COMPLETED','reason','First cut done'));
 perform order_action(staff_id,oid,'assign',jsonb_build_object('assigned_to',next_id,'reason','Private production reassignment'));
 denied:=false; begin perform order_production_action(staff_id,oid,'status','{"status":"ON_HOLD","reason":"Old staff"}'); exception when raise_exception then denied:=true; end;
 if not denied then raise exception 'Prior staff changes production'; end if;
 perform set_config('request.jwt.claim.sub',sa::text,true); execute 'set local role authenticated';
 if exists(select 1 from projects where id=pid) or exists(select 1 from project_milestones where project_id=pid) then raise exception 'Prior staff keeps production RLS'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',na::text,true); execute 'set local role authenticated';
 if not exists(select 1 from projects where id=pid) or not exists(select 1 from project_milestones where project_id=pid) then raise exception 'Current staff lacks production RLS'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',ca::text,true); execute 'set local role authenticated';
 if not exists(select 1 from projects where id=pid) or not exists(select 1 from project_milestones where project_id=pid) then raise exception 'Owner lacks production RLS'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',aa::text,true); execute 'set local role authenticated';
 denied:=false; begin update projects set production_status='COMPLETED' where id=pid; exception when raise_exception or insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Authenticated admin bypasses production workflow'; end if;
 execute 'reset role';
 if (select count(*) from invoices)<>invoice_count then raise exception 'Production creates premature invoice'; end if;
 if not exists(select 1 from conversation_messages where conversation_id=(select id from conversations where request_id=rid) and kind='PROJECT') or not exists(select 1 from audit_logs where entity_id=rid and action='PRODUCTION_CREATED') then raise exception 'Production card/audit missing'; end if;
 if has_function_privilege('authenticated','order_production_action(uuid,uuid,text,jsonb)','execute') or has_function_privilege('service_role','legacy_project_action_024(uuid,uuid,text,jsonb)','execute') then raise exception 'Production/legacy base RPC exposure'; end if;
end $$;
