import { Link, useSearchParams } from "react-router-dom";
import { useAuth } from "../../contexts/AuthContext";
import { useApi } from "../../hooks/useApi";
import { money, Page, Pagination, State, Status } from "../../components/ui";
import { requestsHome } from "../../lib/requests";

type Totals = { consultations:number; closed_orders:number; booked:number; variations:number; received:number; receivable:number; managed_receivable:number; unattributed_orders:number };
type Report = { summary:Totals; staff:(Totals & {staff_id:string|null;full_name:string})[]; items:{id:string;order_number:string;request_id:string;status:string;total:number;collected:number;remaining:number;received_in_period:number;assigned_name:string;closed_name:string|null;accepted_at:string}[];page:number;total:number;limit:number };
export function FinanceReportPage() {
 const {role}=useAuth(), admin=role==='ADMIN', [params,setParams]=useSearchParams();
 const today=new Date(), year=params.get('year') || String(today.getFullYear()), month=params.get('month') || String(today.getMonth()+1), staff=params.get('staff_id') || '';
 const query=useApi<Report>(`/finance/report?${new URLSearchParams({year,month,page:params.get('page') || '1',...(staff?{staff_id:staff}:{})})}`);
 const people=useApi<{id:string;full_name:string;active:boolean}[]>(admin?'/finance/staff':null);
 const change=(key:string,value:string)=>{const next=new URLSearchParams(params);next.set('year',year);next.set('month',month);if(value)next.set(key,value);else next.delete(key);next.delete('page');setParams(next);};
 return <Page title={admin?'Thống kê tài chính & nhân viên':'Thống kê công việc & tài chính của tôi'}>
  <p>Số liệu tính theo đơn dịch vụ. Giá trị đơn đã chốt và tiền thực nhận được thống kê riêng. Khoản thu chỉ được tính sau khi đối soát thực tế; báo chuyển khoản đang chờ xác minh chưa được cộng.</p>
  <div className="toolbar finance-filters"><label>Năm<select value={year} onChange={e=>change('year',e.target.value)}>{Array.from({length:Math.max(1,today.getFullYear()-2017)},(_,i)=>today.getFullYear()+2-i).map(y=><option key={y} value={y}>{y}</option>)}</select></label><label>Kỳ<select value={month} onChange={e=>change('month',e.target.value)}><option value="0">Cả năm</option>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>Tháng {i+1}</option>)}</select></label>{admin&&<label>Nhân viên<select value={staff} onChange={e=>change('staff_id',e.target.value)}><option value="">Toàn công ty</option>{people.data?.map(p=><option value={p.id} key={p.id}>{p.full_name}{!p.active?' · Ngừng hoạt động':''}</option>)}</select></label>}<button className="btn btn-ghost" onClick={query.reload} disabled={query.loading}>Làm mới số liệu</button></div>
  {people.error&&<p className="error" role="alert">{people.error}</p>}
  <State query={query}>{query.data&&<>
   <div className="request-metrics finance-metrics">{[[query.data.summary.consultations,'Yêu cầu đã tiếp nhận trong kỳ'],[query.data.summary.closed_orders,'Đơn chốt trong kỳ'],[money(query.data.summary.booked),'Giá trị đơn chốt trong kỳ'],[money(query.data.summary.variations),'Phát sinh chốt trong kỳ'],[money(query.data.summary.received),'Thực nhận trong kỳ'],[money(query.data.summary.receivable),'Còn phải thu · theo người chốt'],[money(query.data.summary.managed_receivable),'Còn phải thu · đang phụ trách']].map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div>
   <p className="muted">Ghi nhận theo nhân viên phụ trách lúc khách chấp nhận báo giá; chuyển người phụ trách sau đó không chuyển ghi nhận. Phát sinh được ghi vào kỳ Customer xác nhận, không cộng ngược vào giá trị chốt của kỳ trước. Tiền nhận trong kỳ có thể thuộc đơn chốt ở kỳ trước. Khoản còn phải thu là số dư đến cuối kỳ của các đơn đang hiệu lực.</p>
   {!!query.data.summary.unattributed_orders&&<p>{query.data.summary.unattributed_orders} đơn cũ trong kỳ chưa lưu nhân viên chốt, được tính vào tổng công ty.</p>}
   {admin&&<section className="panel"><h2>Thống kê theo nhân viên</h2><div className="table-wrap"><table><thead><tr><th>Nhân viên chốt</th><th>Tiếp nhận</th><th>Đơn chốt</th><th>Giá trị chốt</th><th>Phát sinh trong kỳ</th><th>Thực nhận</th><th>Còn phải thu</th></tr></thead><tbody>{query.data.staff.map(s=><tr key={s.staff_id || 'unknown'}><td>{s.staff_id?<button className="btn btn-ghost" onClick={()=>change('staff_id',s.staff_id!)}>{s.full_name}</button>:s.full_name}</td><td>{s.consultations}</td><td>{s.closed_orders}</td><td>{money(s.booked)}</td><td>{money(s.variations)}</td><td>{money(s.received)}</td><td>{money(s.receivable)}</td></tr>)}</tbody></table></div></section>}
   <section className="panel"><h2>Đơn và khoản còn phải thu</h2><p className="muted">Danh sách gồm các đơn chốt trước cuối kỳ. Staff xem chi tiết các đơn hiện đang phụ trách.</p><div className="table-wrap"><table><thead><tr><th>Đơn dịch vụ</th><th>Người chốt / phụ trách</th><th>Giá trị</th><th>Đã nhận tới cuối kỳ</th><th>Nhận trong kỳ</th><th>Còn thiếu</th></tr></thead><tbody>{query.data.items.map(o=><tr key={o.id}><td><Link to={`${requestsHome(role)}/${o.request_id}`}>{o.order_number}</Link><br/><Status value={o.status}/></td><td>{o.closed_name || 'Chưa lưu người chốt'}<br/><small>Phụ trách: {o.assigned_name}</small></td><td>{money(o.total)}</td><td>{money(o.collected)}</td><td>{money(o.received_in_period)}</td><td>{money(o.remaining)}</td></tr>)}</tbody></table></div>{!query.data.items.length&&<p>Chưa có đơn trong phạm vi thống kê này.</p>}<Pagination page={query.data.page} total={query.data.total} limit={query.data.limit} onChange={page=>{const next=new URLSearchParams(params);next.set('page',String(page));setParams(next);}}/></section>
  </>}</State>
 </Page>;
}
