import { useOrderUpdates } from "../../hooks/useOrderUpdates";
import { useEffect, useState } from "react";
import { ActionForm, Field, State, Status } from "../../components/ui";
import { useAuth } from "../../contexts/AuthContext";
import { useApi } from "../../hooks/useApi";
import { api, post } from "../../services/api";
import { isCustomerRole } from "../../lib/permissions";

type Submission={id:string;assignment_id:string;author_id:string;kind:'REVIEW'|'FINAL';title:string;note:string;file_name:string;file_type:string;file_size:number;final_of:string|null;created_at:string};
type Round={id:string;version:number;submission_ids:string[];note:string;status:string;submitted_at:string;response_note:string|null};
type Delivery={files:Submission[];rounds:Round[];people:{id:string;full_name:string}[];status:string;production_status:string|null;assignment_id:string|null;funds_confirmed:boolean};
export function OrderDeliveryPanel({id,onChanged}:{id:string;onChanged:()=>void}) {
 const {role}=useAuth(), customer=isCustomerRole(role),creator=role==='CREATOR'||role==='STUDENT_CREATOR',operator=role==='STAFF'||role==='ADMIN';
 const query=useApi<Delivery>(`/delivery/${id}`),[selected,setSelected]=useState<string[]>([]),[downloadError,setDownloadError]=useState(''),[uploadKey,setUploadKey]=useState(0);
 useOrderUpdates(id,query.reload);
 const data=query.data,round=data?.rounds[0],accepted=data?.rounds.find(r=>r.status==='ACCEPTED');
 const changed=()=>{query.reload();onChanged();};
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')query.reload()};const timer=window.setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh)}},[id]);
 const finalTargets=(data?.files ?? []).filter(f=>f.kind==='REVIEW'&&f.assignment_id===data?.assignment_id&&accepted?.submission_ids.includes(f.id)&&!data?.files.some(v=>v.final_of===f.id));
 async function download(file:Submission){try{setDownloadError('');const link=await api<{signedUrl:string}>(`/delivery/${id}/files/${file.id}/download`);window.open(link.signedUrl,'_blank','noopener,noreferrer')}catch(e){setDownloadError((e as Error).message)}}
 return <section className="panel contract-panel" id="delivery"><header><h2>Nghiệm thu &amp; bàn giao</h2><button className="btn btn-ghost" onClick={changed} disabled={query.loading}>Làm mới sản phẩm</button></header>
  <p className="muted">Nghiệm thu trên bản có watermark. Sau khi người phụ trách xác nhận thu đủ, Creator bàn giao cùng nội dung đã nghiệm thu với watermark được loại bỏ.</p>
  <State query={query}>{data&&<>
   {data.production_status&&<p><Status value={data.production_status}/></p>}
   {data.status==='COMPLETED'&&<p className="contract-evidence">Đã nghiệm thu, xác nhận thu đủ và nhận toàn bộ bản hoàn thiện. Dự án đã hoàn thành; đội Creator kết thúc phân công.</p>}
   {creator&&data.assignment_id&&data.status==='IN_PROGRESS'&&['IN_PROGRESS','REVISION'].includes(data.production_status || '')&&(!round||round.status==='REVISION_REQUESTED')&&<details><summary>Tải bản nghiệm thu có watermark</summary><ActionForm key={uploadKey} label="Gửi bản nghiệm thu" onSubmit={async f=>{const body=new FormData();body.append('kind','REVIEW');body.append('title',String(f.get('review-title')));body.append('note',String(f.get('review-note') || ''));body.append('confirmed',f.get('review-confirmed')==='on'?'true':'false');body.append('file',f.get('review-file') as File);return api(`/delivery/${id}/files`,{method:'POST',body})}} onSuccess={()=>{setUploadKey(k=>k+1);changed();}}><Field name="review-title" label="Tên sản phẩm / phiên bản"/><Field name="review-note" label="Nội dung đã thực hiện" type="textarea" required={false}/><label className="field">Tệp bản nghiệm thu · tối đa 50 MB<input name="review-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.mp4,.mov" required/></label><label className="contract-checkbox"><input name="review-confirmed" type="checkbox" required/><span>Tôi đã chèn watermark hoặc ký hiệu trên bản nghiệm thu này.</span></label></ActionForm></details>}
   {round&&<article className="quote-card"><header><strong>Vòng nghiệm thu {round.version}</strong><Status value={round.status}/></header><p className="preserve-lines">{round.note}</p><p>{round.submission_ids.length} tệp · {new Date(round.submitted_at).toLocaleString('vi-VN')}</p>{round.response_note&&<p className="preserve-lines">Phản hồi: {round.response_note}</p>}
    {customer&&round.status==='PENDING'&&<><ActionForm label="Xác nhận nghiệm thu kết quả" onSubmit={f=>post(`/delivery/${id}/accept_review`,{round_id:round.id,confirmed:f.get('review-accepted')==='on'})} onSuccess={changed}><label className="contract-checkbox"><input name="review-accepted" type="checkbox" required/><span>Tôi đã xem đủ {round.submission_ids.length} tệp trong vòng này và đồng ý với kết quả theo phạm vi hợp đồng.</span></label></ActionForm><details><summary>Yêu cầu chỉnh sửa theo phạm vi đã thống nhất</summary><ActionForm label="Gửi yêu cầu chỉnh sửa" onSubmit={f=>post(`/delivery/${id}/request_revision`,{round_id:round.id,note:f.get('revision-note')})} onSuccess={changed}><Field name="revision-note" label="Chỉ rõ sản phẩm và nội dung cần chỉnh" type="textarea"/></ActionForm></details></>}
   </article>}
   {accepted&&data.status!=='COMPLETED'&&<p className="notice">{data.funds_confirmed?'Người phụ trách đã xác nhận thu đủ. Đang chờ Creator bàn giao toàn bộ bản không watermark.':'Đã nghiệm thu. Bản không watermark được mở sau khi khách thanh toán phần còn thiếu và người phụ trách xác nhận thu đủ.'}</p>}
   {creator&&data.funds_confirmed&&accepted&&finalTargets.length>0&&<details><summary>Bàn giao bản hoàn thiện không watermark</summary><ActionForm key={`final-${uploadKey}`} label="Bàn giao bản hoàn thiện" onSubmit={async f=>{const target=data.files.find(v=>v.id===f.get('final-of'));if(!target)throw new Error('Chọn bản đã nghiệm thu thuộc phần việc của bạn.');const body=new FormData();body.append('kind','FINAL');body.append('title',target.title);body.append('final_of',target.id);body.append('confirmed',f.get('final-confirmed')==='on'?'true':'false');body.append('file',f.get('final-file') as File);return api(`/delivery/${id}/files`,{method:'POST',body})}} onSuccess={()=>{setUploadKey(k=>k+1);changed();}}><label className="field">Bản đã nghiệm thu<select name="final-of" required><option value="">Chọn bản cần bàn giao</option>{finalTargets.map(f=><option key={f.id} value={f.id}>{f.title} · {f.file_name}</option>)}</select></label><label className="field">Tệp hoàn thiện · tối đa 50 MB<input name="final-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.mp4,.mov" required/></label><label className="contract-checkbox"><input name="final-confirmed" type="checkbox" required/><span>Bản này giữ nguyên nội dung khách đã nghiệm thu và đã loại bỏ watermark/ký hiệu.</span></label></ActionForm></details>}
   <h3>Phiên bản sản phẩm</h3>{downloadError&&<p className="error" role="alert">{downloadError}</p>}{!data.files.length&&<p>Chưa có sản phẩm bàn giao.</p>}
   {operator&&data.files.length>0&&!accepted&&round?.status!=='PENDING'&&<button className="btn btn-ghost" onClick={()=>{const latest=new Map<string,string>();for(const f of data.files)if(f.kind==='REVIEW'&&!latest.has(`${f.assignment_id}:${f.title}`))latest.set(`${f.assignment_id}:${f.title}`,f.id);setSelected([...latest.values()]);}}>Chọn bản mới nhất theo Creator và tên sản phẩm</button>}
   {data.files.map(f=><article key={f.id} className="delivery-file"><strong>{f.title}</strong><p>{f.kind==='FINAL'?'Bản hoàn thiện không watermark':'Bản nghiệm thu có watermark'}{round?.submission_ids.includes(f.id)?` · Thuộc vòng ${round.version}`:''}</p><small>{data.people.find(p=>p.id===f.author_id)?.full_name} · {f.file_name} · {Math.ceil(f.file_size/1024)} KB</small><p className="preserve-lines">{f.note}</p><button className="btn btn-ghost" onClick={()=>download(f)}>Tải phiên bản này</button>{operator&&f.kind==='REVIEW'&&!accepted&&round?.status!=='PENDING'&&<label className="contract-checkbox"><input type="checkbox" checked={selected.includes(f.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,f.id]:s.filter(v=>v!==f.id))}/><span>Đưa vào vòng nghiệm thu tiếp theo</span></label>}</article>)}
   {operator&&selected.length>0&&!accepted&&round?.status!=='PENDING'&&<ActionForm label={`Gửi nghiệm thu ${selected.length} tệp`} onSubmit={f=>post(`/delivery/${id}/send_review`,{submission_ids:selected,note:f.get('send-review-note')})} onSuccess={()=>{setSelected([]);changed();}}><Field name="send-review-note" label="Nội dung bàn giao và tiêu chí nghiệm thu theo hợp đồng" type="textarea"/><p className="muted">Cần chốt hoặc đóng mọi yêu cầu phát sinh, hoàn thành cả các mốc phụ lục và có bản nghiệm thu của toàn bộ đội. Staff kiểm tra nội dung trước khi gửi khách.</p></ActionForm>}
   {data.rounds.length>1&&<details><summary>Lịch sử nghiệm thu</summary>{data.rounds.slice(1).map(r=><article className="production-history" key={r.id}><strong>Vòng {r.version}</strong><Status value={r.status}/><p>{r.note}</p><p>{r.response_note}</p></article>)}</details>}
  </>}</State>
 </section>;
}
