import { Router } from "express";
import { z } from "zod";
import { randomUUID } from "node:crypto";
import { db, result, ApiError } from "./db.js";
import { uuid } from "./validators.js";
export const messagingRoutes=Router(); const client=db as any;
async function member(cid:string,pid:string){const row=await result<any>(client.from("conversation_members").select("conversation_id").eq("conversation_id",cid).eq("profile_id",pid).maybeSingle());if(!row)throw new ApiError(404,"NOT_FOUND","Không tìm thấy cuộc trò chuyện.");const c=await result<any>(client.from("conversations").select("request_id").eq("id",cid).maybeSingle());if(c?.request_id)throw new ApiError(409,"REQUEST_WORKSPACE","Vui lòng mở hội thoại trong workspace yêu cầu dịch vụ.")}
async function internalOnly(cid:string){const ms=await result<any[]>(client.from("conversation_members").select("profile_id").eq("conversation_id",cid));const ps=await result<any[]>(client.from("profiles").select("id,role").in("id",ms.map(m=>m.profile_id)));if(ps.some(p=>!["STAFF","ADMIN"].includes(p.role)))throw new ApiError(403,"REQUEST_REQUIRED","Customer và Creator trao đổi trong hội thoại dịch vụ được phân công.")}
messagingRoutes.get("/",async(req,res)=>{const mine=await result<any[]>(client.from("conversation_members").select("conversation_id,last_read_at,muted,archived").eq("profile_id",req.identity.id).eq("archived",false));const ids=mine.map(x=>x.conversation_id);if(!ids.length)return res.json({success:true,data:[]});const [rows,members]=await Promise.all([result<any[]>(client.from("conversations").select("*").in("id",ids).is("request_id",null).order("last_message_at",{ascending:false})),result<any[]>(client.from("conversation_members").select("conversation_id,profile_id,last_read_at").in("conversation_id",ids))]);const pids=[...new Set(members.map(x=>x.profile_id))];const profiles=pids.length?await result<any[]>(client.from("profiles").select("id,full_name,avatar_url,role").in("id",pids)):[];res.json({success:true,data:rows.map(c=>{const m=mine.find(x=>x.conversation_id===c.id);return{...c,members:members.filter(x=>x.conversation_id===c.id).map(x=>profiles.find(p=>p.id===x.profile_id)).filter(Boolean),unread:!m?.last_read_at||new Date(c.last_message_at)>new Date(m.last_read_at)}})});});
messagingRoutes.post("/",async(req,res)=>{if(!["STAFF","ADMIN"].includes(req.identity.role))throw new ApiError(403,"REQUEST_REQUIRED","Trao đổi dịch vụ trong hội thoại yêu cầu; không tạo chat riêng với Creator.");const body=z.object({creator_id:uuid.optional(),profile_id:uuid.optional(),subject:z.string().trim().max(160).default("")}).refine(x=>x.creator_id||x.profile_id).parse(req.body);let recipientId=body.profile_id;if(body.creator_id){const c=await result<any>(client.from("creator_profiles").select("profile_id,display_name").eq("id",body.creator_id).maybeSingle());if(!c?.profile_id)throw new ApiError(409,"CREATOR_OFFLINE","Creator này chưa kích hoạt nhắn tin.");recipientId=c.profile_id}if(recipientId===req.identity.id)throw new ApiError(422,"INVALID_RECIPIENT","Không thể tự nhắn tin.");const recipient=await result<any>(client.from("profiles").select("id,full_name,role").eq("id",recipientId).eq("active",true).maybeSingle());if(!recipient)throw new ApiError(404,"RECIPIENT_NOT_FOUND","Không tìm thấy người nhận.");if(!["STAFF","ADMIN"].includes(recipient.role))throw new ApiError(403,"REQUEST_REQUIRED","Customer và Creator trao đổi trong hội thoại dịch vụ được phân công.");const id=randomUUID();await result(client.from("conversations").insert({id,subject:body.subject||`Trao đổi với ${recipient.full_name}`}));await result(client.from("conversation_members").insert([{conversation_id:id,profile_id:req.identity.id,last_read_at:new Date().toISOString()},{conversation_id:id,profile_id:recipient.id}]));res.status(201).json({success:true,data:{id}});});
messagingRoutes.get("/:id",async(req,res)=>{const id=uuid.parse(req.params.id);await member(id,req.identity.id);const limit=z.coerce.number().int().min(1).max(100).default(50).parse(req.query.limit);const before=z.iso.datetime().optional().parse(req.query.before);let q=client.from("conversation_messages").select("id,conversation_id,sender_id,content,attachments,created_at").eq("conversation_id",id).order("created_at",{ascending:false}).limit(limit);if(before)q=q.lt("created_at",before);const messages=(await result<any[]>(q)).reverse();const conversation=await result<any>(client.from("conversations").select("*").eq("id",id).single());const ms=await result<any[]>(client.from("conversation_members").select("profile_id,last_read_at").eq("conversation_id",id));const profiles=await result<any[]>(client.from("profiles").select("id,full_name,avatar_url,role").in("id",ms.map(x=>x.profile_id)));res.json({success:true,data:{conversation,messages,members:ms.map(m=>({...m,...profiles.find(p=>p.id===m.profile_id)}))}});});
messagingRoutes.post("/:id/messages",async(req,res)=>{if(!["STAFF","ADMIN"].includes(req.identity.role))throw new ApiError(403,"REQUEST_REQUIRED","Hãy trao đổi trong hội thoại dịch vụ được phân công.");const id=uuid.parse(req.params.id);await member(id,req.identity.id);await internalOnly(id);const body=z.object({content:z.string().trim().min(1).max(5000),attachments:z.array(z.url()).max(6).default([])}).strict().parse(req.body);const message=await result(client.from("conversation_messages").insert({conversation_id:id,sender_id:req.identity.id,...body}).select().single());await result(client.from("conversation_members").update({last_read_at:new Date().toISOString()}).eq("conversation_id",id).eq("profile_id",req.identity.id));res.status(201).json({success:true,data:message});});
messagingRoutes.post("/:id/read",async(req,res)=>{const id=uuid.parse(req.params.id);await member(id,req.identity.id);await result(client.from("conversation_members").update({last_read_at:new Date().toISOString()}).eq("conversation_id",id).eq("profile_id",req.identity.id));res.json({success:true,data:{read:true}});});
