import { useState } from "react";
import { ActionForm, Field, Page, Pagination, State, money } from "../../components/ui";
import { useApi } from "../../hooks/useApi";
import { patch, post } from "../../services/api";
import type { ServicePackage } from "../../types/requests";
type Collection<T> = { items: T[]; total: number };
export function AdminServicePackages() {
  const services = useApi<Collection<{ id: string; name: string }>>("/admin/services?limit=100");
  const [service, setService] = useState(""), [page, setPage] = useState(1), [editing, setEditing] = useState<ServicePackage | null>(null), [creating, setCreating] = useState(false);
  const query = useApi<Collection<ServicePackage>>(`/admin/service-packages?page=${page}${service ? `&service_id=${service}` : ""}`);
  return <Page title="Gói dịch vụ"><p>Quản lý phạm vi, đầu ra và giá tham khảo. Thay đổi gói không sửa snapshot trong những brief đã gửi.</p><State query={services}><div className="toolbar"><label>Dịch vụ <select aria-label="Lọc gói theo dịch vụ" value={service} onChange={e => { setService(e.target.value); setPage(1); }}><option value="">Tất cả</option>{services.data?.items.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="btn btn-primary" onClick={() => { setEditing(null); setCreating(true); }}>Thêm gói dịch vụ</button></div>
    {(creating || editing) && <section className="panel"><h2>{editing ? "Sửa gói dịch vụ" : "Gói dịch vụ mới"}</h2><ActionForm key={editing?.id || "new"} label="Lưu gói" onSubmit={form => {
      const optional = (key: string) => String(form.get(key) || "").trim() ? Number(form.get(key)) : null;
      const body = { service_id: editing?.service_id || form.get("service_id"), name: form.get("name"), description: form.get("description") || "", starting_price: optional("starting_price"), estimated_days: optional("estimated_days"), deliverables: String(form.get("deliverables") || "").split(/\r?\n/).map(line => line.trim()).filter(Boolean), active: form.get("active") === "true", display_order: Number(form.get("display_order") || 0) };
      return editing ? patch(`/admin/service-packages/${editing.id}`, body) : post("/admin/service-packages", body);
    }} onSuccess={() => { setEditing(null); setCreating(false); query.reload(); }}><div className="field"><label htmlFor="package-service">Dịch vụ</label><select id="package-service" name="service_id" required defaultValue={editing?.service_id || service} disabled={!!editing}><option value="">Chọn dịch vụ</option>{services.data?.items.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><Field name="name" label="Tên gói" value={editing?.name} /><Field name="description" label="Phạm vi gói" type="textarea" value={editing?.description} required={false} /><div className="request-form-grid"><Field name="starting_price" label="Giá tham khảo từ (VND)" type="number" value={editing?.starting_price ?? undefined} required={false} /><Field name="estimated_days" label="Số ngày dự kiến" type="number" value={editing?.estimated_days ?? undefined} required={false} /><Field name="display_order" label="Thứ tự hiển thị" type="number" value={editing?.display_order ?? 0} /><div className="field"><label htmlFor="package-active">Công bố gói</label><select id="package-active" name="active" defaultValue={editing?.active ? "true" : "false"}><option value="false">Chưa công bố / Ngừng cung cấp</option><option value="true">Đang cung cấp</option></select></div></div><Field name="deliverables" label="Sản phẩm bàn giao (mỗi dòng một mục, tối đa 30)" type="textarea" value={editing?.deliverables.join("\n")} required={false} /></ActionForm><button className="btn btn-ghost" onClick={() => { setEditing(null); setCreating(false); }}>Đóng form</button></section>}
    <State query={query}><div className="request-list">{query.data?.items.map(pack => <article className="panel request-list-card" key={pack.id}><div><small>{services.data?.items.find(s => s.id === pack.service_id)?.name}</small><h2>{pack.name}</h2><p>{pack.description}</p><p>{pack.starting_price === null ? "Giá theo tư vấn" : "Tham khảo từ " + money(pack.starting_price)} · {pack.active ? "Đang cung cấp" : "Chưa công bố"}</p><small>{pack.deliverables.join(" · ")}</small></div><button className="btn btn-ghost" onClick={() => { setEditing(pack); setCreating(false); }}>Sửa gói</button></article>)}</div>{!query.data?.items.length && <p className="panel">Chưa có gói dịch vụ trong phạm vi này.</p>}<Pagination page={page} total={query.data?.total ?? 0} onChange={setPage} /></State>
  </State></Page>;
}
