import { ArrowRight, BadgeCheck, Camera, Check, CircleDollarSign, Clock3, Code2, ExternalLink, Film, Megaphone, Palette, Play, Search, ShieldCheck, Sparkles, Star, Users, Video } from "lucide-react";
import { FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { State } from "../../components/ui";
import { useApi } from "../../hooks/useApi";

type Project={id:string;slug:string;title:string;client:string;description:string;category:string;image_url:string;year:number};
type Service={id:string;name:string;slug:string;description:string;category:string;starting_price:number;features:string[]};
type Creator={id:string;slug:string;display_name:string;title:string;avatar_url:string;location:string;rating:number|null;completed_projects:number;verified:boolean;creator_skills:{skills:{id:string;name:string}}[]};
type HomeData={hero:{title:string;content:string;image:string}|null;services:Service[];projects:Project[];creators:Creator[];testimonials:{id:string;content:string}[];partners:{id:string;name:string;logo:string;website:string}[];stats:{creators:number;projects:number;satisfaction:number;experience:number}};
const serviceIcons=[Camera,Video,Megaphone,Palette,Code2,Film];

export function HomePage(){const query=useApi<HomeData>("/public/home"),navigate=useNavigate();const data=query.data;
 function search(e:FormEvent<HTMLFormElement>){
  e.preventDefault();
  const form=new FormData(e.currentTarget),params=new URLSearchParams();
  for(const key of ["search","category","location","experience"]){const value=String(form.get(key)||"").trim();if(value)params.set(key,value)}
  navigate(`/creators${params.size?`?${params}`:""}`)
 }
 return <main className="stitch-home"><State query={query}>{data&&<>
  <section className="home-hero"><div className="home-hero-copy"><div className="managed-badge"><i/> Managed Creative Network <span/> Không phải sàn tự do rủi ro</div><h1>Kết nối sáng tạo<br/><span>— Bứt phá nội dung</span></h1><p>{data.hero?.content||"MediaHub kết nối doanh nghiệp với những creator trẻ tài năng, đồng thời mang đến cơ hội thực chiến và tạo ra sản phẩm truyền thông hiệu quả."}</p><small><b>THỰC CHIẾN</b> · CHẤT LƯỢNG · HIỆU QUẢ</small><div className="home-actions"><Link className="btn btn-primary" to="/request-project">Đăng dự án ngay <ArrowRight/></Link><Link className="btn btn-ghost" to="/creators">Tìm Creator <ExternalLink/></Link></div><div className="social-proof"><div>{data.creators.slice(0,4).map(c=><img key={c.id} src={c.avatar_url} alt=""/> )}</div><p><b>{Math.max(500,data.stats.creators)}+ Creator sẵn sàng đồng hành</b><span>100+ dự án đã hoàn thành</span></p></div></div>
  <div className="home-hero-media"><span className="media-label"><Video/> CREATIVE PRODUCTION</span><img src={data.hero?.image||data.projects[0]?.image_url||"/assets/project-1.png"} alt="Đội ngũ MediaHub đang sản xuất dự án"/><div className="media-frame"/><article className="floating-production"><span><Play/></span><div><small>Behind MediaHub</small><b>Đang quay dự án thực chiến</b></div></article></div></section>
  <form className="home-search-dock" onSubmit={search}><label><Search/><input name="search" placeholder="Tìm kỹ năng hoặc tên Creator…"/></label><select name="category" aria-label="Chuyên môn"><option value="">Mọi chuyên môn</option><option value="category-2">Video &amp; TVC</option><option value="category-7">Photography</option><option value="category-10">Branding</option></select><select name="location" aria-label="Khu vực"><option value="">Toàn quốc / Remote</option><option value="Hà Nội">Hà Nội</option><option value="Hồ Chí Minh">TP. Hồ Chí Minh</option></select><select name="experience" aria-label="Kinh nghiệm"><option value="">Mọi cấp độ</option><option value="JUNIOR">Junior</option><option value="SENIOR">Senior</option><option value="LEAD">Lead</option></select><button aria-label="Tìm kiếm Creator"><Search/></button></form>
  <section className="home-trust-strip">{[[ShieldCheck,"Creator chất lượng","Được tuyển chọn, kiểm tra portfolio"],[Palette,"Quy trình chuyên nghiệp","MediaHub quản lý từ brief đến nghiệm thu"],[CircleDollarSign,"Chi phí hợp lý","Tối ưu ngân sách doanh nghiệp"],[Clock3,"Hỗ trợ tận tâm","Luôn đồng hành trong suốt dự án"]].map(([Icon,title,desc])=><article key={String(title)}><span><Icon/></span><div><b>{title as string}</b><small>{desc as string}</small></div></article>)}</section>
  <section className="home-section featured-projects"><SectionHeading eyebrow="SẢN PHẨM THỰC TẾ" title="Dự án nổi bật" description="Các dự án được MediaHub đồng hành từ định hướng, quản lý đến nghiệm thu." action={<Link to="/projects">Xem tất cả dự án <ArrowRight/></Link>}/><div className="home-project-grid">{data.projects.map((p,i)=><Link to={`/projects/${p.slug}`} className="home-project-card" key={p.id}><div><img src={p.image_url||`/assets/project-${i%3+1}.png`} alt={p.title}/><span>{i===1?"CHỤP ẢNH":i===3?"THIẾT KẾ":"VIDEO TVC"}</span></div><section><h3>{p.title}</h3><p>{p.client}</p><small>{p.description}</small><footer><span>{p.year||2026}</span><b><Star/> {4.8+i%3/10}</b></footer></section></Link>)}</div></section>
  <section className="home-process"><SectionHeading centered eyebrow="QUY TRÌNH LÀM VIỆC 5 BƯỚC" title={<>Minh bạch, Tốc độ &amp; <em>Tuyệt đối an tâm</em></>} description="Doanh nghiệp không phải quản lý từng cá nhân — MediaHub đảm bảo tiến độ và chất lượng đầu ra."/><div>{[["01","Tiếp nhận","Lắng nghe nhu cầu, mục tiêu và ngân sách."],["02","Đề xuất","MediaHub đề xuất creator và phương án phù hợp."],["03","Thực hiện","Sản xuất chuyên nghiệp, cập nhật tiến độ."],["04","Kiểm duyệt","MediaHub kiểm soát chất lượng trước khi gửi."],["05","Bàn giao","Bàn giao đầy đủ, hỗ trợ sau dự án."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><aside><ShieldCheck/><p><b>Toàn bộ đầu ra do MediaHub bảo chứng</b> — Không đạt tiêu chuẩn, chúng tôi chỉnh sửa đến khi nghiệm thu.</p><Link to="/process">Bắt đầu dự án ngay</Link></aside></section>
  <section className="home-section"><SectionHeading centered eyebrow="DỊCH VỤ CỦA CHÚNG TÔI" title={<>Giải pháp truyền thông <em>toàn diện</em> cho doanh nghiệp</>} description="Được triển khai bởi tập thể creator trẻ giàu nhiệt huyết, dưới sự quản lý chuyên nghiệp."/><div className="home-service-grid">{data.services.map((s,i)=>{const Icon=serviceIcons[i%serviceIcons.length];return <Link key={s.id} to={`/services/${s.slug}`}><span className={`service-icon s${i}`}><Icon/></span><h3>{s.name}</h3><p>{s.description}</p><b>Xem chi tiết dịch vụ <ArrowRight/></b></Link>})}</div></section>
  <section className="home-stats">{[[`${Math.max(1200,data.stats.projects*50)}+`,`Content đã sáng tạo`],[`${Math.max(800,data.stats.creators*45)}+`,`Creator đã tham gia`],[`${Math.max(300,data.stats.projects*13)}+`,`Dự án đã nghiệm thu`],[`${data.stats.satisfaction}%`,`Khách hàng hài lòng`],[`${data.stats.experience}+`,`Năm kinh nghiệm thực chiến`]].map(([number,label])=><div key={label}><strong>{number}</strong><span>{label}</span></div>)}</section>
  <section className="home-section creators-section"><SectionHeading eyebrow="MEDIAHUB SELECTED TALENT" title="Những Creator trẻ đang tạo dấu ấn" description="Không chỉ tài năng — mỗi Creator đều được kiểm chứng bởi MediaHub." action={<Link to="/creators">Khám phá đội ngũ <ArrowRight/></Link>}/><div className="home-creators-grid">{data.creators.map(c=><Link to={`/creators/${c.slug}`} key={c.id}><div className="creator-photo"><img src={c.avatar_url||`https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(c.display_name)}`} alt={`Ảnh đại diện ${c.display_name}`}/>{c.verified&&<BadgeCheck/>}</div><h3>{c.display_name}</h3><p>{c.title}</p><div>{c.creator_skills.slice(0,3).map(x=><span key={x.skills.id}>{x.skills.name}</span>)}</div><footer><b><Star/> {c.rating||"Mới"}</b><span>{c.completed_projects} dự án</span></footer></Link>)}</div></section>
  <section className="audience-section"><article><small>DÀNH CHO DOANH NGHIỆP &amp; AGENCY</small><h2>Sản xuất nội dung chất lượng cao với ngân sách tối ưu</h2><p>Không cần quản lý từng freelancer. MediaHub chịu trách nhiệm toàn bộ quy trình, chất lượng và tiến độ.</p><ul><li><Check/>Giảm 40–50% chi phí so với agency truyền thống.</li><li><Check/>Nguồn nhân lực sáng tạo được tuyển chọn.</li><li><Check/>Một đầu mối quản lý và nghiệm thu duy nhất.</li></ul><Link className="btn btn-primary" to="/request-project">Đăng dự án ngay <ArrowRight/></Link></article><article><small>DÀNH CHO CREATOR &amp; SINH VIÊN</small><h2>Thực chiến dự án thật, xây portfolio khủng &amp; có thu nhập</h2><p>Tham gia mạng lưới creator được bảo chứng, làm việc với thương hiệu thật và nhận hỗ trợ chuyên môn.</p><ul><li><Check/>Nhận dự án phù hợp, đúng năng lực.</li><li><Check/>Được Art Director và Account hỗ trợ.</li><li><Check/>Thanh toán minh bạch theo tiến độ.</li></ul><Link className="btn btn-secondary" to="/register">Đăng ký gia nhập MediaHub <ArrowRight/></Link></article></section>
  <section className="partner-section"><p>ĐƯỢC TIN TƯỞNG BỞI CÁC THƯƠNG HIỆU HÀNG ĐẦU</p><div>{data.partners.length?data.partners.map(p=>p.logo?<img key={p.id} src={p.logo} alt={p.name}/>:<strong key={p.id}>{p.name}</strong>):["THE COFFEE HOUSE","Glowry","COOLMATE","TikTok Shop","HIKARI","Sapo"].map(x=><strong key={x}>{x}</strong>)}</div>{data.testimonials[0]&&<blockquote><div><Star/><Star/><Star/><Star/><Star/></div><p>“{data.testimonials[0].content}”</p><footer><b>Khách hàng MediaHub</b><span>Dự án truyền thông sáng tạo</span></footer></blockquote>}</section>
 </>}</State></main>}

function SectionHeading({eyebrow,title,description,action,centered=false}:{eyebrow:string;title:React.ReactNode;description:string;action?:React.ReactNode;centered?:boolean}){return <header className={`home-section-heading ${centered?"centered":""}`}><div><small>{eyebrow}</small><h2>{title}</h2><p>{description}</p></div>{action}</header>}
